import type { OmBirlaProfile } from "./types";

export const OM_BIRLA_PROFILE: OmBirlaProfile = {
  id: "ls-4716",
  slug: "om-birla",
  fullName: "Om Birla",
  displayName: "Om Birla",
  alsoKnownAs: ["Shri Om Birla", "Birla, Shri Om"],
  birth: {
    date: "1962-11-23",
    displayDate: "23 November 1962",
    place: "Kota, Rajasthan, India",
    parents: {
      father: "Shrikrishna Birla",
      mother: "Late Smt. Shakuntala Devi",
    },
    familyBackground:
      "Born into a Marwari Hindu family in Kota. Associated with the Rashtriya Swayamsevak Sangh and its student wing ABVP from youth; joined student politics at school level.",
  },
  personal: {
    spouse: "Dr. Amita Birla (m. 1991)",
    marriageYear: "1991",
    children: "Two daughters — Akansha Birla and Anjali Birla",
    childrenNote:
      "Official Lok Sabha roster omits family details; secondary sources consistently report two daughters. One compilation (OneIndia) lists four children — retained here as a recorded variation, with the two-daughter record treated as primary.",
    profession: ["Politician", "Businessperson", "Social worker"],
    website: "https://ombirla.in",
    party: "Bharatiya Janata Party",
    partyAbbreviation: "BJP",
  },
  education: [
    {
      degree: "M.Com.",
      institution: "Government Commerce College, Kota",
      university: "Maharshi Dayanand Saraswati University, Ajmer",
      year: "1987 (Post-graduation); Graduation 1985",
      field: "Commerce",
    },
  ],
  officesHeld: [
    {
      office: "President, Students' Union, Government Senior Secondary School, Gumanpura, Kota",
      jurisdiction: "Kota, Rajasthan",
      term: "1979",
      entryMethod: "Direct election (student body)",
      notes: "First electoral win at age 17.",
    },
    {
      office: "District President, Bharatiya Janata Yuva Morcha (BJYM), Kota",
      jurisdiction: "Rajasthan",
      term: "1987–1991",
      entryMethod: "Organisational appointment",
    },
    {
      office: "State President, BJYM, Rajasthan",
      jurisdiction: "Rajasthan",
      term: "1991–1997 (some secondary reports record 1993–1997)",
      entryMethod: "Organisational appointment",
    },
    {
      office: "Vice Chairman, National Co-operative Consumer Federation Limited (NCCF), New Delhi",
      jurisdiction: "National",
      term: "Early 1990s (concurrent with state BJYM presidency)",
      entryMethod: "Cooperative sector appointment",
    },
    {
      office: "Chairman, Rajasthan State Cooperative Consumer Federation Ltd. (CONFED), Jaipur",
      jurisdiction: "Rajasthan",
      term: "June 1992 – June 1995",
      entryMethod: "Cooperative sector appointment",
    },
    {
      office: "National Vice President, BJYM",
      jurisdiction: "National",
      term: "1997–2003",
      entryMethod: "Organisational appointment (served during J.P. Nadda's tenure as BJYM president)",
    },
    {
      office: "Member of Legislative Assembly, Kota South",
      jurisdiction: "Rajasthan Legislative Assembly",
      term: "December 2003 – May 2014 (three terms: 12th, 13th, 14th Rajasthan Assembly)",
      entryMethod: "Direct election (FPTP)",
      predecessor: "Shanti Kumar Dhariwal (from undifferentiated Kota before bifurcation)",
      successor: "Sandeep Sharma",
      notes:
        "2003: defeated Shanti Dhariwal (INC) by 10,101 votes; 2008: defeated Ram Kishan Verma (INC) by 24,300 votes; 2013: defeated Pankaj Mehta (INC) by ~50,000 votes.",
    },
    {
      office: "Parliamentary Secretary (MoS rank), Government of Rajasthan",
      jurisdiction: "Rajasthan",
      term: "2003–2008 (reported variously as 2004–2008)",
      entryMethod: "Appointment by Chief Minister Vasundhara Raje",
      notes:
        "Facilitated financial assistance of up to Rs. 50 lakh for poor and seriously ill patients through the state government.",
    },
    {
      office: "Member of Parliament, Lok Sabha, Kota (Kota-Bundi)",
      jurisdiction: "Parliament of India — Lok Sabha",
      term: "16th Lok Sabha (2014–2019), 17th (2019–2024), 18th (2024–present)",
      entryMethod: "Direct election (FPTP)",
      predecessor: "Ijyaraj Singh (INC)",
      notes:
        "2014: defeated Ijyaraj Singh (INC) by >2,00,000 votes; 2019: defeated Ramnarayan Meena (INC) by ~2.5 lakh votes; 2024: re-elected from Kota (opponent reported as Prahlad Gunjal, INC) — becoming first Speaker in 20 years to be re-elected as MP after serving as Speaker.",
    },
    {
      office: "Speaker of the Lok Sabha (17th Lok Sabha)",
      jurisdiction: "Parliament of India",
      term: "19 June 2019 – 24 June 2024 (house dissolved 2024)",
      entryMethod: "Elected by the House; motion moved by Prime Minister Narendra Modi; elected unanimously",
      predecessor: "Sumitra Mahajan",
      notes: "Youngest speakers at the time; unanimous election; tenure under BJP majority (303 seats).",
    },
    {
      office: "Speaker of the Lok Sabha (18th Lok Sabha)",
      jurisdiction: "Parliament of India",
      term: "26 June 2024 – present (incumbent)",
      entryMethod:
        "Elected by voice vote after a rare contest (first since 1976) — NDA nominee vs. K. Suresh (INC, INDIA bloc, 8-time MP from Mavelikara, Kerala); motion moved by PM Modi, seconded by Shiv Sena (UBT) MP Arvind Sawant for the opposition candidate",
      notes:
        "First person in 20 years re-elected as Speaker after serving a full term; joined Balram Jakhar, G.S. Dhillon, M.A. Ayyangar, P.A. Sangma, G.M.C. Balayogi as multi-term Speakers.",
    },
  ],
  timeline: [
    {
      date: "1962-11-23",
      dateLabel: "23 November 1962",
      title: "Born in Kota, Rajasthan",
      description:
        "Born to Shrikrishna Birla and Shakuntala Devi in a Marwari Hindu family. Hometown Kota remains his parliamentary constituency base.",
      category: "birth",
      citationIds: ["wiki", "toi", "oneindia"],
    },
    {
      date: "1978",
      dateLabel: "1978",
      title: "Early protest as ABVP member",
      description:
        "As a member of Akhil Bharatiya Vidyarthi Parishad, participated in a protest against unemployment in Kota and came before the car of Minister Bhanwar Lal Sharma in the Janata Party government of Bhairon Singh Shekhawat — an early marker of his youth-activist profile.",
      category: "youth",
      citationIds: ["theprint", "firstpost"],
    },
    {
      date: "1979",
      dateLabel: "1979 · Age 17",
      title: "President, Students' Union — Govt. Sr. Sec. School, Gumanpura",
      description:
        "Won his first election as president of the student union at Government Senior Secondary School, Gumanpura, Kota. Later associated with the RSS as a primary member.",
      category: "youth",
      citationIds: ["wiki", "express", "oneindia"],
    },
    {
      date: "1985",
      dateLabel: "1985",
      title: "Graduation in Commerce",
      description:
        "Completed graduate studies in Commerce at Government Commerce College, Kota. National-level commentary notes completion in 1985, followed by post-graduation in 1987.",
      category: "education",
      citationIds: ["wiki", "express", "toI2"],
    },
    {
      date: "1987",
      dateLabel: "1987 · Graduated + BJYM district president",
      title: "Post-graduation and entry to BJYM leadership",
      description:
        "Completed M.Com. at Government Commerce College, Kota / Maharshi Dayanand Saraswati University, Ajmer (1987). Same year became District President, BJYM Kota (1987–1991). Later reports conflate Rajasthan University, Jaipur — the Kota/MDSU record is treated as primary.",
      category: "education",
      citationIds: ["wiki", "oneindia", "economictimes"],
    },
    {
      date: "1987-1991",
      dateLabel: "1987–1991",
      title: "District President, BJYM Kota",
      description:
        "Led the BJP youth wing at district level in Kota, building booth-level organisation that later became a noted party strength.",
      category: "youth",
      citationIds: ["wiki", "toi"],
    },
    {
      date: "1991-1997",
      dateLabel: "1991–1997",
      title: "State President, BJYM Rajasthan",
      description:
        "State president of BJYM Rajasthan for six years (some secondary sources record 1993–1997). Concurrently engaged in the cooperative sector — Vice Chairman, National Co-operative Consumer Federation Ltd., and Chairman, CONFED Jaipur (June 1992–June 1995).",
      category: "youth",
      citationIds: ["wiki", "toi", "oneindia"],
    },
    {
      date: "1992-1995",
      dateLabel: "June 1992 – June 1995",
      title: "Chairman, CONFED Jaipur; Vice Chairman, NCCF",
      description:
        "Chairman of Rajasthan State Cooperative Consumer Federation (CONFED) Jaipur and Vice Chairman of the National Cooperative Consumer Federation Ltd., New Delhi. Developed the Super Bazar network concept nationally; later served as Director of Coal India.",
      category: "cooperative",
      citationIds: ["wiki", "oneindia"],
    },
    {
      date: "1997-2003",
      dateLabel: "1997–2003",
      title: "National Vice President, BJYM",
      description:
        "National Vice President of Bharatiya Janata Yuva Morcha during J.P. Nadda's tenure as BJYM chief. National exposure helped build cross-state party relationships; also associated with the Ram Temple movement (reported arrest in Uttar Pradesh) and cooperative leadership.",
      category: "youth",
      citationIds: ["wiki", "theprint", "oneindia"],
    },
    {
      date: "2001",
      dateLabel: "January 2001",
      title: "Gujarat earthquake relief — led 100 volunteers",
      description:
        "Led a team of 100 volunteers, including doctors, to Gujarat following the January 2001 earthquake — cited as part of his social-work profile that later earned Delhi leadership attention.",
      category: "social",
      citationIds: ["express"],
    },
    {
      date: "2003-12",
      dateLabel: "December 2003",
      title: "First MLA — Kota South (giant-killer)",
      description:
        "Fielded by Rajasthan BJP president Vasundhara Raje against Congress stalwart Shanti Dhariwal, won by 10,101 votes — earning the 'giant-killer' label. Held the seat as the region's established leaders (Lalit Kishore Chaturvedi, Raghuveer Singh Kaushal) faded.",
      category: "assembly",
      citationIds: ["wiki", "express", "theprint"],
    },
    {
      date: "2003-2008",
      dateLabel: "2003–2008",
      title: "Parliamentary Secretary (MoS rank), Rajasthan Government",
      description:
        "Appointed Parliamentary Secretary by Chief Minister Vasundhara Raje. Used the office to channel up to Rs. 50 lakh per serious patient case through state assistance; served on Estimate Committee 'A' (2004).",
      category: "assembly",
      citationIds: ["wiki", "oneindia"],
    },
    {
      date: "2008",
      dateLabel: "2008",
      title: "Second Assembly term — Kota South",
      description:
        "Re-elected, defeating Ram Kishan Verma (INC) by 24,300 votes. Continued as MLA while the relationship with Raje's camp cooled — later shifted focus to national politics.",
      category: "assembly",
      citationIds: ["wiki", "toi"],
    },
    {
      date: "2013",
      dateLabel: "2013",
      title: "Third Assembly term — Kota South",
      description:
        "Third consecutive win from Kota South, defeating Pankaj Mehta (INC) by close to 50,000 votes. This was his last state term before contesting the Lok Sabha.",
      category: "assembly",
      citationIds: ["wiki", "toi", "economictimes"],
    },
    {
      date: "2014-05",
      dateLabel: "May 2014",
      title: "Elected to 16th Lok Sabha — Kota",
      description:
        "As BJP candidate for Kota, elected to the 16th Lok Sabha, defeating Ijyaraj Singh (INC) by more than two lakh votes. Member: Standing Committee on Energy; Consultative Committee for Ministry of Social Justice and Empowerment; also served on Petitions, Estimates (Sub-Committee-III from 2015) and Joint Committee on Citizenship (Amendment) Bill, 2016 (from 2017).",
      category: "parliament",
      citationIds: ["wiki", "oneindia", "timesofindia"],
    },
    {
      date: "2015-03",
      dateLabel: "March 2015",
      title: "Ek Mutthi Ann Rahat Abhiyaan",
      description:
        "Launched a food-grain collection and distribution campaign for hailstorm-affected farmers in rural Kota-Bundi — one of his earliest constituency-wide social initiatives as MP.",
      category: "social",
      citationIds: ["oneindia"],
    },
    {
      date: "2019-05",
      dateLabel: "May 2019",
      title: "Re-elected to 17th Lok Sabha",
      description:
        "Re-elected from Kota, defeating Ramnarayan Meena (INC) by ~2.5 lakh votes. Consolidated his position as the BJP's Kota anchor.",
      category: "parliament",
      citationIds: ["wiki", "oneindia"],
    },
    {
      date: "2019-06-19",
      dateLabel: "19 June 2019",
      title: "Elected Speaker — 17th Lok Sabha (unanimous)",
      description:
        "Motion moved by Prime Minister Modi; elected unanimously as the 17th Lok Sabha Speaker, succeeding Sumitra Mahajan. Among the youngest Speakers. Assumed ex-officio roles: Chairperson of Business Advisory Committee, Rules Committee, General Purposes Committee; President of Indian Parliamentary Group and CPA India Region; Chair, Standing Committee of All India Presiding Officers' Conference.",
      category: "speakership",
      citationIds: ["wiki", "ombirla", "prs", "sansad"],
    },
    {
      date: "2019-2024",
      dateLabel: "2019–2024",
      title: "First speakership — reforms and record",
      description:
        "Promoted transition to a paperless Lok Sabha and greater use of Hindi in proceedings. The 17th Lok Sabha passed a high volume of bills. Critics cited limited consensus-building, brief discussions (e.g., Monsoon Session: 22 bills averaging ~40 minutes) and the December 13–21, 2023 suspension of 100 Lok Sabha MPs (146 across both Houses) for disrupting business — the largest single-session suspension then recorded.",
      category: "speakership",
      citationIds: ["theprint", "ombirla", "firstpost", "express"],
    },
    {
      date: "2024-06",
      dateLabel: "June 2024",
      title: "Re-elected to 18th Lok Sabha and as Speaker (voice vote)",
      description:
        "Elected to the 18th Lok Sabha from Kota-Bundi for a third term (defeated Prahlad Gunjal). On 26 June 2024, elected Speaker of the 18th Lok Sabha by voice vote as the NDA nominee, defeating K. Suresh (INDIA bloc) — the first contested Speaker election since 1976 (only the second since 1952). Became the first presiding officer in 20 years re-elected as MP after serving as Speaker, and one of the few to hold the Speaker's chair twice.",
      category: "speakership",
      citationIds: ["wiki", "toi", "express", "theprint", "firstpost"],
    },
    {
      date: "2024-06-09",
      dateLabel: "9 June 2024 – present",
      title: "Incumbent — 18th Lok Sabha & Speaker",
      description:
        "As of the latest accessible official trackers (PRS: data 24 June 2024–13 August 2026), shows as sitting MP from Kota, BJP, Third Term, attendance/debates/questions marked N/A or zero — by convention the Speaker does not sign attendance or participate in debates/questions. Holds the Speaker's office under President Droupadi Murmu (earlier Ram Nath Kovind).",
      category: "speakership",
      citationIds: ["prs", "wiki"],
    },
    {
      date: "2026-02-10",
      dateLabel: "10 February 2026 (reported)",
      title: "No-confidence notice (reported, per secondary source)",
      description:
        "A secondary summary records that INDIA Alliance members submitted a no-confidence notice seeking removal of Speaker Birla to Lok Sabha Secretary-General Utpal Kumar Singh bearing ~119 signatures. The House status of such a motion is determined solely by the official Lok Sabha record; reproduced here as a reported, attributed claim with citation.",
      category: "speakership",
      citationIds: ["wiki"],
    },
  ],
  socialInitiatives: [
    {
      name: "Medicine Bank (Nishulk Dawa Yojna)",
      since: "As MP",
      description:
        "Free medicines for the poor through a medicine bank funded by donations and CSR — covers cancer and thalassemia support, distributing wheelchairs/tricycles to the differently abled.",
      citationIds: ["oneindia"],
    },
    {
      name: "Prasadam — free food service",
      since: "As MP",
      description: "Free cooked food distribution for attendants and the needy around hospitals and public places in Kota-Bundi.",
      citationIds: ["oneindia"],
    },
    {
      name: "Nishulk Paridhan Uphaar Kendra",
      since: "As MP",
      description: "Free clothing distribution centre for the underprivileged.",
      citationIds: ["oneindia"],
    },
    {
      name: "Meri Paathshala — portable schools",
      since: "As MP",
      description: "Portable schools in slums for out-of-school children from marginalised communities.",
      citationIds: ["oneindia"],
    },
    {
      name: "Matru Gyan Kendras & Suposhit Maa Abhiyan",
      since: "As MP",
      description: "Rural maternal nutrition and awareness centres tackling malnutrition among mothers and children.",
      citationIds: ["oneindia"],
    },
    {
      name: "Rain Baseras & Kambal Nidhi Prakalp",
      since: "As MP",
      description: "Modern night shelters for labourers and blanket distribution for the homeless in winter.",
      citationIds: ["oneindia"],
    },
    {
      name: "Ek Mutthi Ann Rahat Abhiyaan",
      since: "March 2015",
      description: "Food-grain relief for hailstorm-affected farmers collected through community contribution.",
      citationIds: ["oneindia"],
    },
    {
      name: "Slippers Distribution Campaign",
      since: "2007",
      description: "Free footwear to prevent heat blisters for the poor in summer.",
      citationIds: ["oneindia"],
    },
    {
      name: "Azadi ke Swar",
      since: "2006",
      description: "Annual Independence Day programme in Kota fostering patriotism and honouring martyrs' families.",
      citationIds: ["oneindia"],
    },
    {
      name: "Green Kota / Green Quota Forestation Campaign",
      since: "As MLA/MP",
      description: "Plantation drives to combat pollution and increase greenery across Kota — linked to his early efforts to bring Chambal river water to Bundi and environmental advocacy.",
      citationIds: ["oneindia", "theprint"],
    },
  ],
  speakership: {
    firstTerm: "19 June 2019 – 24 June 2024 (17th Lok Sabha, unanimous election)",
    secondTerm: "26 June 2024 – present (18th Lok Sabha, elected by voice vote)",
    predecessor: "Sumitra Mahajan",
    historicNotes: [
      "One of the youngest persons to serve as Lok Sabha Speaker at first election.",
      "First presiding officer in 20 years re-elected to the Lok Sabha after serving as Speaker.",
      "Only the second contested Speaker election since 1952 (first since 1976).",
      "Among the few Speakers to hold the office twice — cohort includes Balram Jakhar (two full 5-year terms), G.S. Dhillon, M.A. Ayyangar, P.A. Sangma, G.M.C. Balayogi.",
    ],
    reforms: [
      "Transition of Lok Sabha toward paperless functioning.",
      "Promotion of Hindi in parliamentary proceedings.",
      "Continuity claim: 'works not done in 70 years made possible under his chair' — PM's congratulatory remark on record (political speech, not a procedural metric).",
    ],
    committeesAndRoles: [
      "Ex-officio Chairperson: Business Advisory Committee, Rules Committee, General Purposes Committee.",
      "President: Indian Parliamentary Group; President, India Union Branch of the Commonwealth Parliamentary Association (CPA).",
      "Chairman: Standing Committee of All India Presiding Officers' Conference; Executive Committee, CPA India Region.",
      "Earlier (16th Lok Sabha): Standing Committee on Energy; Consultative Committee, Ministry of Social Justice and Empowerment; Committee on Estimates (Sub-Committee-III from 2015); Committee on Petitions; Joint Committee on Citizenship (Amendment) Bill, 2016.",
    ],
    criticisms: [
      "Opposition criticism that suspensions during 13–21 December 2023 (100 Lok Sabha MPs, 146 across both Houses) were unprecedented and that bills were passed with limited discussion (e.g., Monsoon session: 22 bills averaging ~40 minutes). Recorded here as reported political assessments, not as adjudicated findings.",
      "Reported no-confidence notice by ~119 INDIA bloc MPs (10 Feb 2026, per secondary summary) — outcome governed solely by official Lok Sabha proceedings.",
    ],
  },
  salaries: [
    {
      office: "President, Students' Union (Govt. Sr. Sec. School, Gumanpura)",
      period: "1979",
      salary: "No salary — student office",
      allowances: "—",
      totalApprox: "Unpaid honorary",
      legalBasis: "Student body",
      notes: "First electoral office at age 17.",
      citationIds: ["wiki"],
    },
    {
      office: "District President, BJYM Kota",
      period: "1987–1991",
      salary: "No salary — party organisational post",
      allowances: "Organisational support only",
      totalApprox: "Unpaid (honorary party work)",
      legalBasis: "BJP organisational appointment",
      citationIds: ["wiki", "toi"],
    },
    {
      office: "State President, BJYM Rajasthan",
      period: "1991–1997",
      salary: "No salary — party post",
      allowances: "—",
      totalApprox: "Unpaid",
      legalBasis: "BJYM organisational",
      citationIds: ["wiki"],
    },
    {
      office: "Vice Chairman, NCCF & Chairman, CONFED (Cooperative sector)",
      period: "1992–1995 (CONFED); early 1990s NCCF",
      salary: "Honorarium / sitting fee as per cooperative bylaws (not a parliamentary salary)",
      allowances: "As per federation rules",
      totalApprox: "Not a legislative salary — cooperative honorarium",
      legalBasis: "Cooperative Societies framework; NCCF/CONFED bylaws",
      notes: "Also served as Director, Coal India (board sitting fee).",
      citationIds: ["wiki", "oneindia"],
    },
    {
      office: "National Vice President, BJYM",
      period: "1997–2003",
      salary: "No salary — national party post",
      allowances: "—",
      totalApprox: "Unpaid",
      legalBasis: "BJP organisational",
      citationIds: ["wiki", "theprint"],
    },
    {
      office: "Member of Legislative Assembly, Kota South (Rajasthan)",
      period: "Dec 2003 – May 2014",
      salary: "Basic ₹40,000 per month (rate from 1 Apr 2019 under Rajasthan Legislative Assembly (Officers & Members Emoluments & Pension) Act, 1956 §4)",
      allowances: "Daily ₹2,000 (in-state) / ₹2,500 (out-state), vehicle ₹30k, sumptuary ₹45k, secretarial ₹30k, travel ₹2 lakh p.a., plus free housing/medical as per Act",
      totalApprox: "~₹1.47 lakh per month with allowances (2025 estimate; ~₹44k basic proposed 10% hike 2025). Historical 2003–2014 basic was lower (≈₹15k–₹25k era).",
      legalBasis: "Rajasthan Legislative Assembly (Officers & Members Emoluments & Pension) Act, 1956 §§4, 8; Bhaskar English 23 Jul 2025; Acadlog compilation",
      notes: "Salary revisions are periodic by state Act; current illustrative total uses 2019–2025 rates. Earlier term rates were lower — shown as range.",
      citationIds: ["rajasthanAct", "bhaskarRajasthan", "acadlogMLA"],
    },
    {
      office: "Parliamentary Secretary (MoS rank), Government of Rajasthan",
      period: "2003–2008",
      salary: "Pay & allowances equivalent to Minister of State, Rajasthan (in addition to MLA salary, not in duplication — as per Rajasthan rules for Parliamentary Secretaries)",
      allowances: "Ministerial perks: staff, vehicle, residence as per MoS entitlement",
      totalApprox: "At MoS scale (state minister) — in addition to MLA pay; exact split governed by GoR notification",
      legalBasis: "Rajasthan Parliamentary Secretary conventions; appointment at MoS rank by CM",
      notes: "Used office to facilitate up to ₹50 lakh financial assistance for patients via state scheme.",
      citationIds: ["wiki", "oneindia"],
    },
    {
      office: "Member of Parliament, Lok Sabha (Kota)",
      period: "2014–2019 (16th), 2019–2024 (17th), 2024–present (18th)",
      salary: "₹1,00,000 pm (1 Apr 2018–31 Mar 2023) → ₹1,24,000 pm (from 1 Apr 2023, notified 24 Mar 2025, G.S.R. 188(E))",
      allowances: "Constituency ₹70k→₹87k + Office/secretarial ₹60k→₹70k + Daily ₹2,000→₹2,500 per sitting day; one-time furniture ₹1 lakh→₹1.25 lakh; plus 34 free air journeys, unlimited 1st-class rail, medical, housing",
      totalApprox: "Assured cash ≈₹2.30 lakh pm (pre-2023) → ₹2.81 lakh pm (post-Apr 2023, excl. daily allowance) — per Economic Times/BS calculations",
      legalBasis: "Salary, Allowances and Pension of Members of Parliament Act, 1954 §§3, 8A (as amended by Finance Act 2018, auto-index to Cost Inflation Index); Notification G.S.R. 188(E) 24 Mar 2025; Business Standard 24 Mar 2025",
      citationIds: ["mpSalaryGazette", "theHinduSalary", "bsSalary", "etSalary"],
    },
    {
      office: "Speaker of the Lok Sabha (17th & 18th)",
      period: "19 Jun 2019 – present",
      salary: "As per Salaries and Allowances of Officers of Parliament Act, 1953 — equated to a Cabinet Minister: same as MP salary plus Speaker's additional entitlements",
      allowances: "Sumptuary ₹1,000 pm (Speaker) + free fully-furnished residence (20 Akbar Road before, Speaker's residence), staff, travel, medical as per Officers of Parliament Act §§4–7; plus MP allowances continua",
      totalApprox: "Cabinet Minister scale (≈ MP assured cash + Speaker perks). No separate ‘Speaker salary’ figure published — governed by Officers of Parliament Act, 1953",
      legalBasis: "Constitution Art. 97 + Salaries and Allowances of Officers of Parliament Act, 1953 (Act 20 of 1953) §§3–5; Second Schedule fallback; MPA NeVA amenities sheet",
      citationIds: ["officersParliamentAct", "article97", "nevaAmenities"],
    },
  ],
  netWorthTimeline: [
    {
      election: "Rajasthan Assembly 2008 — Kota South",
      year: "2008",
      totalAssets: "₹1,19,85,906 (~₹1.19 Cr)",
      movable: "~₹17.2 lakh",
      immovable: "~₹1.02 Cr",
      liabilities: "₹5,00,000 (~₹5 lakh)",
      cases: "0 (per 2008 affidavit on Myneta)",
      citationIds: ["mynetaCompare", "myneta2008"],
    },
    {
      election: "Rajasthan Assembly 2013 — Kota South",
      year: "2013",
      totalAssets: "₹2,69,98,488 (~₹2.69 Cr)",
      movable: "~₹? (see affidavit)",
      immovable: "~₹? (combined)",
      liabilities: "₹10,75,186 (~₹10.75 lakh)",
      cases: "2 (IPC 143, 332, 353, 283) — charges/ cognizance, no conviction",
      citationIds: ["mynetaCompare"],
    },
    {
      election: "Lok Sabha 2014 — Kota",
      year: "2014",
      totalAssets: "₹2,58,70,497 (~₹2.58 Cr)",
      movable: "~₹? (comparable)",
      immovable: "~₹? (comparable)",
      liabilities: "~standalone 2014 affidavit; see compare",
      cases: "2 (IPC 143, 283, 332, 353; Sec 3 PDPP; cases 550/13, 17/13 — cognizance taken 2012–13, no conviction)",
      citationIds: ["myneta2014", "mynetaCompare", "adr2014_2024"],
    },
    {
      election: "Lok Sabha 2019 — Kota (Winner)",
      year: "2019",
      totalAssets: "₹4,83,47,737 (~₹4.83 Cr) — incl. self ~₹29.47 lakh movable + ₹92 lakh immovable; spouse ~₹1.17 Cr movable + ₹2.41 Cr immovable",
      movable: "₹1,50,47,737 (~₹1.50 Cr) incl. deposits ₹55.41 lakh, jewellery ₹2.97 lakh, vehicle ₹3.86 lakh (self car)",
      immovable: "₹3,33,00,000 (~₹3.33 Cr) incl. agricultural land 34.8 acres (₹32 lakh self) + buildings",
      liabilities: "Nil (disclosed)",
      cases: "1 (FIR 224/12, P.S. Modak, Case 896/2018, JM Ramganjmandi, IPC 143 & 283 + Sec 8(b) National Highway Act — charges framed 22 Jan 2019; no conviction)",
      incomeSelf: "₹7,97,000 p.a. (2019)",
      incomeSpouse: "₹25,36,000 p.a. (2019, Dr. Amita — govt doctor)",
      citationIds: ["myneta2019", "mynetaCompare", "adr2014_2024"],
    },
    {
      election: "Lok Sabha 2024 — Kota (Winner, 3rd term)",
      year: "2024",
      totalAssets: "₹10,62,06,645 (~₹10.62 Cr) — 311% rise over 2014 (₹2.58→₹10.62 Cr); ~120% over 2019 (₹4.83→₹10.62 Cr)",
      movable: "₹5.2 Cr (incl. bank deposits ₹2.80 Cr combined — self ₹1.85 Cr in 4 a/cs vs ₹19.75 lakh in 5 a/cs in 2019; spouse ₹94.94 lakh vs ₹35.50 lakh in 2019)",
      immovable: "₹5.5 Cr (incl. agri land 34.8 acres now ₹40 lakh; wife 28.95 acres ₹35 lakh; wife house/flat ₹4.49 Cr; self immovable now ₹58 lakh — no separately-owned house disclosed; earlier ₹60 lakh Jaipur house not repeated)",
      liabilities: "Nil",
      cases: "0 (2024 affidavit: ‘No criminal cases’)",
      incomeSelf: "₹13,79,000 p.a. (2024)",
      incomeSpouse: "₹22,19,000 p.a. (2024, retired)",
      citationIds: ["myneta2024", "mynetaCompare", "timesNowAsset", "etvAsset", "adr2014_2024", "indiatv2024"],
    },
  ],
  netWorthNotes: [
    "All figures are self-declared in election affidavits filed with the Election Commission of India (ECI) and compiled by ADR/Myneta. ‘Movable’ includes cash, deposits, jewellery (self: 50g gold + 8.74 kg silver in 2019 → same weight, now ~₹9 lakh; spouse: 806g gold→1.426 kg gold, 57→94 ct diamond, 10.21 kg→30.47 kg silver, now ~₹30.63 lakh), vehicles (self car ₹3.86 lakh in 2019 → ₹2 lakh in 2024 after depreciation; spouse 2 cars ₹12.51 lakh → 1 car ₹3 lakh), and investments.",
    "Immovable jump is largely a valuation effect (wife’s immovable ₹2.41 Cr→₹4.87 Cr on market revision) plus reclassification of the earlier Jaipur house. Agricultural holdings unchanged by area (self 34.8 acres, spouse 28.95 acres) — value revised from ₹32→₹40 lakh and ₹28→₹35 lakh.",
    "Liabilities: 2014/13 affidavits showed ₹5–10 lakh loans; 2019 and 2024 show Nil. Incomes: combined self+spouse ₹33.33 lakh (2019) → ₹36 lakh (2024). Annualised asset growth for 102 three-term re-elected MPs averaged 110% (₹15.76 Cr in 2014 → ₹33.13 Cr in 2024) — Birla’s 311% is above that cohort average (ADR 2014–2024 study).",
    "No assets marked as ‘House’ in own name in 2024 (ETVBharat/NDTV phrasing: ‘no house in own name’). The house remains shown under spouse name. Verify against the 2024 affidavit PDF on ECI/Myneta for line-item breakup.",
  ],
  workHighlights: [
    {
      title: "Paperless Lok Sabha & digital transition",
      date: "2019–2024",
      kind: "positive",
      summary: "As 17th Speaker, pushed the House toward a paperless workflow (e-notices, tablets, NeVA integration) — listed on his official site and reported as a reform.",
      sourceLabel: "ombirla / ThePrint",
      citationId: "ombirla",
    },
    {
      title: "Hindi promotion in proceedings",
      date: "2019–2024",
      kind: "positive",
      summary: "Encouraged greater use of Hindi in debates and questions — cited among his procedural priorities.",
      sourceLabel: "ombirla",
      citationId: "ombirla",
    },
    {
      title: "High productivity claims",
      date: "2024–2025",
      kind: "mixed",
      summary: "Home Minister Amit Shah cited in Lok Sabha (Mar 2026): Budget Session 118% productivity last year; 16th/17th/18th Lok Sabha avg 91% each — ‘highest since Indira Gandhi era’. Also cited: 17th Lok Sabha gave Congress (52 MPs) 157h 55m vs BJP (303 MPs) 349h 08m — i.e. ~6× more time per MP to opposition. Government-side stat — treat as claim.",
      sourceLabel: "Akashvani / The Hindu",
      citationId: "akashvaniProd",
    },
    {
      title: "Regional languages: 14 languages permitted",
      date: "Mar 2026",
      kind: "positive",
      summary: "Cited in the no-confidence reply: regional language use significantly expanded — permission to debate in ~14 languages.",
      sourceLabel: "Akashvani",
      citationId: "akashvaniProd",
    },
    {
      title: "Booth-management system credited inside BJP",
      date: "Profile note (Express/ThePrint)",
      kind: "positive",
      summary: "Credited within BJP circles for developing the party’s booth-management software and grassroots organisation — grassroots booth worker identity rather than a tech-manager.",
      sourceLabel: "Indian Express",
      citationId: "express",
    },
    {
      title: "Mass suspensions: 100 Lok Sabha MPs (13–21 Dec 2023) — 146 across both Houses",
      date: "Dec 2023",
      kind: "critical",
      summary: "Presided over the largest single-session suspension on record (100 Lok Sabha, 146 total) after disruption over the security-breach debate — cited by opposition as evidence of intolerance for dissent; treasury side cited as enforcing discipline after disorder. Accounts for >40% of all Lok Sabha suspensions since 2004 per TMC MP Mahua Moitra.",
      sourceLabel: "The Wire / ThePrint / The Hindu",
      citationId: "wireNoConfidence",
    },
    {
      title: "Bills passed with brief discussion (Monsoon example: 22 bills ~40 min avg)",
      date: "2023 Monsoon",
      kind: "critical",
      summary: "Opposition and press critique: key bills pushed through with limited debate — average ~40 minutes per bill in the Monsoon Session example. Government view: House productivity requires time-bound disposal.",
      sourceLabel: "ThePrint / Firstpost",
      citationId: "theprint",
    },
    {
      title: "Mic-muting and Sansad TV camera-angle allegations",
      date: "2023–2025",
      kind: "critical",
      summary: "Opposition alleged microphones muted (e.g., Shashi Tharoor Feb 9) and Sansad TV showing only the Chair when opposition spoke, BJP when treasury spoke. Speaker has denied controlling mics; opposition letter Mar 2025 raised 12 issues including BAC disregard, adjournment-motion denial, and camera angles.",
      sourceLabel: "The Wire",
      citationId: "wireNoConfidence",
    },
    {
      title: "No-confidence motion and its defeat (voice vote)",
      date: "10–12 Mar 2026 debated; notice 10 Feb 2026",
      kind: "mixed",
      summary: "INDIA bloc (118–119 MPs) moved Article 94(c) no-confidence vs Speaker citing partisan conduct (Rahul Gandhi speech bar on Naravane memoir/Caravan, 8-mp suspension 3 Feb, Nishikant Dubey books vs Rule 349, women-MPs/PM-chair allegations, mic & BAC issues). Defeated by voice vote 12 Mar 2026; Speaker returned to Chair stating impartiality and that the debate allowed all views.",
      sourceLabel: "The Wire / ToI / Akashvani",
      citationId: "toiNoConfidenceReject",
    },
  ],
  allegations: [
    {
      title: "Criminal cases in affidavits (no convictions)",
      date: "2012–2019 cases; affidavits 2014/2019/2024",
      allegation: "Declared pending criminal cases under IPC 143 (unlawful assembly), 283 (public way obstruction), 332/353 (hurt/assault to deter public servant) + Sec 8(b) National Highway Act / Sec 3 PDPP Act.",
      context: "2014: 2 cases (550/13 cognizance 21 Dec 2012, 17/13 cognizance 8 Jan 2013 — ACJ(JD) JM Kota). 2019: 1 case (FIR 224/12 PS Modak, Case 896/2018 JM Ramganjmandi, IPC 143/283 + NH Act — charges framed 22 Jan 2019). 2024: 0 cases. All relate to protests/agitations — typical for political-office affidavits.",
      responseOrStatus: "No conviction in any case (Myneta ‘Cases where Convicted — No Cases’ for all three). 2024 affidavit declares zero pending cases. Status to be verified against latest ECI affidavit and court records.",
      outcome: "No conviction; latest affidavit clean. Earlier cases appear disposed/not repeated.",
      citationIds: ["myneta2019", "myneta2014", "myneta2024", "mynetaCompare"],
    },
    {
      title: "‘Partisan Speaker’ — suspension & speech-bar allegations (no-confidence grounds)",
      date: "2019–2026; crystallised Feb–Mar 2026",
      allegation: "Opposition alleged blatantly partisan conduct: barred LoP Rahul Gandhi from quoting Caravan/Naravane memoir under Rules 349/353; interrupted LoP ~20 times; suspended 100 Lok Sabha MPs Dec 2023 (plus 46 Rajya Sabha) and 8 MPs 3 Feb 2026; allowed BJP MP Nishikant Dubey to violate the same Rule 349 with books; made ‘baseless’ claims about women MPs planning to surround PM’s chair; denied BAC decisions and adjournment motions; muted mics; kept Deputy Speaker vacant 7 years.",
      context: "Motion moved under Constitution Art. 94(c) read with Rules; debated 10–12 Mar 2026 in Lok Sabha with ~42 MPs speaking; panel chair Jagdambika Pal presided (opposition objected as Pal was Speaker-nominated and Deputy Speaker vacant — govt cited Art. 95(2)). Only the 4th such motion in history (1954 vs Mavalankar, 1966 vs Hukam Singh — failed to get 50 supporters, 1987 vs Jakhar).",
      responseOrStatus: "Speaker denied mic control; defended impartiality; said concrete information justified advising PM not to come 5 Feb to avoid ‘black-spot’ incident in chamber/office. Treasury defended productivity, time allocation to opposition, and Speaker’s impartial role. Home Minister Amit Shah called questioning Speaker’s integrity ‘regrettable’. ",
      outcome: "Motion defeated by voice vote 12 Mar 2026 (The Wire, ToI, Akashvani). Speaker returned stating ‘No one above rules’, pledging dedication, impartiality and constitutional propriety. Productivity and time-share figures cited as defence.",
      citationIds: ["wireNoConfidence", "newsMinuteNoConfidence", "toiPartisan", "toiNoConfidenceReject", "printNoConfidence", "wireSafeguarding", "akashvaniProd", "businessTodayExplain"],
    },
    {
      title: "Deputy Speaker vacancy — 7 years without election",
      date: "2019–2026",
      allegation: "Opposition cited failure to elect Deputy Speaker ‘as soon as may be’ per Art. 93 — constitutional convention to give post to opposition flouted; created ‘constitutional vacuum’ especially when Speaker’s removal was debated without a neutral presiding officer.",
      context: "17th and 18th Lok Sabha ran without a Deputy Speaker; panel of chairpersons (Speaker-nominated) presided. Comparisons drawn to earlier Lok Sabhas where opposition held Deputy Speaker post.",
      responseOrStatus: "Parliamentary Affairs Minister Kiren Rijiju argued ‘many things happen for first time in parliamentary traditions’ and that Speaker has final authority where rules are silent; no election scheduled as of Mar 2026 reporting.",
      citationIds: ["wireNoConfidence", "newsMinuteNoConfidence"],
    },
    {
      title: "Expulsion/suspension context: Mahua Moitra (2023) and others",
      date: "Dec 2023",
      allegation: "TMC MP Mahua Moitra cited her 2023 expulsion and the 100-MP suspension bloc as part of a pattern where Speaker did not afford opposition adequate hearing or defence time.",
      context: "Moitra’s remark during no-confidence debate: the Dec 2023 suspensions alone accounted for >40% of Lok Sabha suspensions since 2004.",
      responseOrStatus: "Speaker’s office maintained suspensions were for disrupting business after the 13 Dec 2023 security breach; Moitra later participated in the Mar 2026 debate. No separate adjudication recorded — political allegation with parliamentary remedy (no-confidence) exercised.",
      citationIds: ["wireSafeguarding", "wireNoConfidence"],
    },
    {
      title: "No financial-corruption allegation found in the record",
      date: "Through 2024 affidavits",
      allegation: "No specific quid-pro-quo, PMLA or Lokpal corruption case attributed to Om Birla in the searched reputable secondary record; ADR/Myneta affidavits show no financial FIR beyond the protest-related IPC sections above.",
      context: "Asset growth (₹2.58 Cr in 2014 → ₹10.62 Cr in 2024) has been noted by press as ‘doubled in 5 years’ but not as the subject of a filed corruption FIR in the retrieved sources. Press reports frame it as bank-deposit and jewellery-valuation growth, not as an allegation of illegality.",
      responseOrStatus: "No filed allegation to rebut as of the last verified search date. Asset details are public via ECI affidavits. Any future complaint would be governed by Lokpal/ED/CBI jurisdiction and ECI disclosure rules — not by this dossier.",
      outcome: "Neutral fact: no corruption allegation on record in the compiled sources — dossier will update if a filed case appears in an authoritative source.",
      citationIds: ["timesNowAsset", "etvAsset", "adr2014_2024", "myneta2024"],
    },
  ],
  citations: {
    wiki: {
      label: "wiki",
      publisher: "Wikipedia — Om Birla",
      title: "Om Birla",
      url: "https://en.wikipedia.org/wiki/Om_Birla",
      accessedOn: "28 August 2026",
    },
    toi: {
      label: "toi",
      publisher: "The Times of India",
      title: "Who is Om Birla, the re-elected speaker of Lok Sabha?",
      url: "https://timesofindia.indiatimes.com/india/who-is-om-birla-the-re-elected-speaker-of-lok-sabha/articleshow/111289745.cms",
      accessedOn: "28 August 2026",
    },
    toI2: {
      label: "toI2",
      publisher: "The Times of India (duplicate)",
      title: "Om Birla biography — Commerce degree",
      url: "https://timesofindia.indiatimes.com/india/who-is-om-birla-the-re-elected-speaker-of-lok-sabha/articleshow/111289745.cms",
      accessedOn: "28 August 2026",
    },
    express: {
      label: "express",
      publisher: "The Indian Express — Political Pulse",
      title: "Om Birla's second innings as Lok Sabha Speaker: Grassroots leader who rose through BJP ranks",
      url: "https://indianexpress.com/article/political-pulse/om-birla-lok-sabha-speaker-bjp-9415992/",
      accessedOn: "28 August 2026",
    },
    theprint: {
      label: "theprint",
      publisher: "ThePrint",
      title: "Nadda's BJYM deputy, BJP's man in Kota — rise & rise of Om Birla",
      url: "https://theprint.in/politics/naddas-bjym-deputy-bjps-man-in-kota-rise-rise-of-om-birla-nda-nominee-for-lok-sabha-speaker/2147259/",
      accessedOn: "28 August 2026",
    },
    firstpost: {
      label: "firstpost",
      publisher: "Firstpost — Explainers",
      title: "Om Birla returns as Lok Sabha Speaker: The rise",
      url: "https://www.firstpost.com/explainers/om-birla-lok-sabha-speaker-rise-of-bjp-kota-mp-13786269.html",
      accessedOn: "28 August 2026",
    },
    oneindia: {
      label: "oneindia",
      publisher: "OneIndia — Politicians / Om Birla",
      title: "Om Birla: Age, Biography, Education, Wife, Caste, Net Worth & More",
      url: "https://www.oneindia.com/politicians/om-birla-35249.html",
      accessedOn: "28 August 2026",
    },
    economictimes: {
      label: "economictimes",
      publisher: "The Economic Times",
      title: "Who is Om Birla, his political career, education and all other details",
      url: "https://m.economictimes.com/news/politics-and-nation/who-is-om-birla-his-political-carrer-education-and-all-other-details/who-is-om-birla/slideshow/111315955.cms",
      accessedOn: "28 August 2026",
    },
    ombirla: {
      label: "ombirla",
      publisher: "Om Birla — Official website",
      title: "Lok Sabha Speaker Om Birla — official site",
      url: "https://ombirla.in/",
      accessedOn: "28 August 2026",
    },
    sansad: {
      label: "sansad",
      publisher: "Parliament of India — Digital Sansad / Lok Sabha Secretariat",
      title: "Hon'ble Speaker — Digital Sansad; List of Members (ls-4716)",
      url: "https://sansad.in/ls/about/speaker",
      accessedOn: "28 August 2026",
    },
    prs: {
      label: "prs",
      publisher: "PRS Legislative Research — MP Track",
      title: "Om Birla — MP Track (18th Lok Sabha)",
      url: "https://prsindia.org/mptrack/18th-lok-sabha/om-birla",
      accessedOn: "28 August 2026",
    },
    josh: {
      label: "josh",
      publisher: "Jagran Josh",
      title: "Om Birla New Lok Sabha Speaker: Biography and Political Career",
      url: "https://www.jagranjosh.com/general-knowledge/om-birla-biography-and-political-career-1560837391-1",
      accessedOn: "28 August 2026",
    },
    rajasthanAct: {
      label: "rajasthanAct",
      publisher: "India Code / Rajasthan Legislative Assembly",
      title: "Rajasthan Legislative Assembly (Officers and Members Emoluments and Pension) Act, 1956 — §4 (Members' salary)",
      url: "https://www.indiacode.nic.in/handle/123456789/18773?locale=en",
      accessedOn: "28 August 2026",
    },
    bhaskarRajasthan: {
      label: "bhaskarRajasthan",
      publisher: "Bhaskar English",
      title: "Rajasthan MLAs likely to get 10% salary hike (basic ₹40k → ₹44k, total ~₹1.47 lakh pm)",
      url: "https://www.bhaskarenglish.in/local/rajasthan/news/mlas-salary-and-ex-mlas-pension-to-rise-in-rajasthan-government-proposes-10-hike-in-basic-pay-pension-hike-details-yet-to-be-finalised-135517628.html",
      accessedOn: "28 August 2026",
    },
    acadlogMLA: {
      label: "acadlogMLA",
      publisher: "Acadlog",
      title: "Rajasthan MLA Salary: Complete Details (basic + vehicle/sumptuary/secretarial/travel breakdown)",
      url: "https://acadlog.com/updates/blog/rajasthan-mla-salary-complete-details",
      accessedOn: "28 August 2026",
    },
    mpSalaryGazette: {
      label: "mpSalaryGazette",
      publisher: "Ministry of Parliamentary Affairs — Gazette of India",
      title: "G.S.R. 188(E) — Notification of 24% hike: salary ₹1,00,000 → ₹1,24,000 pm, daily ₹2,000→₹2,500, pension ₹25k→₹31k (eff. 1 Apr 2023, notified 24 Mar 2025)",
      url: "https://getapi.indiatvnews.com/doc/261888.pdf",
      accessedOn: "28 August 2026",
    },
    theHinduSalary: {
      label: "theHinduSalary",
      publisher: "The Hindu",
      title: "Centre notifies 24% hike in salaries, pensions for MPs",
      url: "https://www.thehindu.com/news/national/centre-notifies-24-hike-in-salaries-pensions-for-mps/article69368455.ece",
      accessedOn: "28 August 2026",
    },
    bsSalary: {
      label: "bsSalary",
      publisher: "Business Standard",
      title: "Hike in MP Salary in 2025: MPs to get ₹1.24 lakh monthly salary",
      url: "https://www.business-standard.com/india-news/members-of-parliament-salary-pension-allowance-increase-government-125032400774_1.html",
      accessedOn: "28 August 2026",
    },
    etSalary: {
      label: "etSalary",
      publisher: "The Economic Times",
      title: "Centre approves 24% salary hike for MPs: Monthly income rises to Rs 1.24 lakh (assured ₹2.81 lakh incl. allowances)",
      url: "https://economictimes.indiatimes.com/news/politics-and-nation/centre-approves-24-salary-hike-for-mps-monthly-income-rises-to-2-81l/articleshow/119438959.cms",
      accessedOn: "28 August 2026",
    },
    officersParliamentAct: {
      label: "officersParliamentAct",
      publisher: "Indian Kanoon / Gazette of India",
      title: "The Salaries and Allowances of Officers of Parliament Act, 1953 (Act 20 of 1953) — §§3–5, residence & sumptuary",
      url: "https://indiankanoon.org/doc/1534878/",
      accessedOn: "28 August 2026",
    },
    article97: {
      label: "article97",
      publisher: "Constitution of India / Lexibal explainer",
      title: "Article 97 — Salaries and allowances of presiding officers (Speaker/Chairman) and Second Schedule fallback",
      url: "https://lexibal.com/article-97-salaries-presiding-officers/",
      accessedOn: "28 August 2026",
    },
    nevaAmenities: {
      label: "nevaAmenities",
      publisher: "Ministry of Parliamentary Affairs — NeVA",
      title: "Amenities to Members / Officers — salary sumptuary sheet (Speaker: Cabinet Minister scale)",
      url: "https://cms.neva.gov.in/NeVA/RS/FileStructures/FooterCommonContent/ac06fbd1-f5ef-4425-9bb3-971532e84357.pdf",
      accessedOn: "28 August 2026",
    },
    mynetaCompare: {
      label: "mynetaCompare",
      publisher: "Association for Democratic Reforms — MyNeta",
      title: "Om Birla — Asset & cases comparison across affidavits (2008, 2013, 2014, 2019, 2024)",
      url: "https://www.myneta.info/compare_profile.php?group_id=23wct4xpkx7ervZo7uF",
      accessedOn: "28 August 2026",
    },
    myneta2008: {
      label: "myneta2008",
      publisher: "MyNeta — ADR",
      title: "OM BIRLA — Kota South 2008 affidavit (₹1.19 Cr assets, 0 cases)",
      url: "https://myneta.info/rj2008/candidate.php?candidate_id=361",
      accessedOn: "28 August 2026",
    },
    myneta2014: {
      label: "myneta2014",
      publisher: "MyNeta — ADR",
      title: "Om Birla — Lok Sabha 2014 affidavit (₹2.58 Cr, 2 cases, cognizance 2012–13)",
      url: "https://myneta.info/ls2014/candidate.php?candidate_id=2409",
      accessedOn: "28 August 2026",
    },
    myneta2019: {
      label: "myneta2019",
      publisher: "MyNeta — ADR",
      title: "Om Birla — Lok Sabha 2019 affidavit (₹4.83 Cr, 1 case FIR 224/12, charges framed 22 Jan 2019)",
      url: "https://myneta.info/LokSabha2019/candidate.php?candidate_id=10788",
      accessedOn: "28 August 2026",
    },
    myneta2024: {
      label: "myneta2024",
      publisher: "MyNeta — ADR / ECI",
      title: "Om Birla — Lok Sabha 2024 affidavit (₹10.62 Cr, 0 cases) and cross-reference",
      url: "https://myneta.info/compare_profile.php?group_id=23wct4xpkx7ervZo7uF",
      accessedOn: "28 August 2026",
    },
    adr2014_2024: {
      label: "adr2014_2024",
      publisher: "Association for Democratic Reforms",
      title: "Analysis of Assets Comparison of Re-Elected MPs 2014–2024 (Om Birla: ₹2.58 Cr → ₹10.62 Cr, +311%) and Avg 110% for 102 MPs",
      url: "https://adrindia.org/sites/default/files/Updated_Analysis_of_Assets_Comparison_of_Re-Elected_MPs_2014_to_2024_Lok_Sabha_Elections_Eng.pdf",
      accessedOn: "28 August 2026",
    },
    timesNowAsset: {
      label: "timesNowAsset",
      publisher: "Times Now News",
      title: "Om Birla Net Worth: Speaker Sees Substantial Asset Growth In Five Years (₹4.79 Cr → ₹10.61 Cr, bank deposits ₹55L → ₹2.80 Cr)",
      url: "https://www.timesnownews.com/business-economy/industry/om-birla-net-worth-lok-sabha-speaker-sees-substantial-asset-growth-in-five-years-article-110686409",
      accessedOn: "28 August 2026",
    },
    etvAsset: {
      label: "etvAsset",
      publisher: "ETV Bharat (Hindi)",
      title: "ओम बिरला के नाम नहीं कोई मकान, 5 साल में दोगुनी हुई संपत्ति — ₹4.79 Cr (2019) → ₹10.61 Cr (2024), car, jewellery, land details",
      url: "https://www.etvbharat.com/hi/!state/lok-sabha-election-2024-lok-sabha-speaker-om-birla-asset-doubled-in-5-years-rjs24040306166",
      accessedOn: "28 August 2026",
    },
    indiatv2024: {
      label: "indiatv2024",
      publisher: "India TV News / ADR",
      title: "Political Profile of Om Birla, Kota, and Net Worth — 2024 affidavit: ₹10.6 Cr total, ₹5.2 Cr movable, ₹5.5 Cr immovable, 0 liabilities, 0 cases",
      url: "https://www.indiatvnews.com/elections/lok-sabha-elections-2024/rajasthan/kota-constituency/candidate-list/om-birla-lok-sabha-candidate",
      accessedOn: "28 August 2026",
    },
    wireNoConfidence: {
      label: "wireNoConfidence",
      publisher: "The Wire",
      title: "Behind the No-Confidence Motion: Why Speaker Om Birla Has Been Accused of Being Partisan (100 LS suspensions, Rule 349/353, 8-mp suspension, mic, deputy vacancy)",
      url: "https://m.thewire.in/article/politics/behind-the-no-confidence-motion-why-speaker-om-birla-has-been-accused-of-being-partisan",
      accessedOn: "28 August 2026",
    },
    newsMinuteNoConfidence: {
      label: "newsMinuteNoConfidence",
      publisher: "The News Minute",
      title: "Why Opposition MPs have moved a no-confidence motion against Om Birla",
      url: "https://www.thenewsminute.com/news/why-opposition-mps-have-moved-a-no-confidence-motion-against-om-birla",
      accessedOn: "28 August 2026",
    },
    toiPartisan: {
      label: "toiPartisan",
      publisher: "The Times of India",
      title: "Om Birla's behaviour partisan, LoP cut off 20 times: Gaurav Gogoi (mic muting, 20 interruptions, Pal chair dispute)",
      url: "https://timesofindia.indiatimes.com/india/om-birlas-behaviour-partisan-lop-cut-off-20-times-gaurav-gogoi/articleshow/129425660.cms",
      accessedOn: "28 August 2026",
    },
    toiNoConfidenceReject: {
      label: "toiNoConfidenceReject",
      publisher: "The Times of India",
      title: "'No one above rules': Om Birla back in Chair after House rejects resolution to remove him (voice vote, 12 Mar 2026)",
      url: "https://timesofindia.indiatimes.com/india/no-one-above-law-in-lok-sabha-om-birla-back-in-chair-after-house-rejects-resolution-to-remove-him/articleshow/129496894.cms",
      accessedOn: "28 August 2026",
    },
    printNoConfidence: {
      label: "printNoConfidence",
      publisher: "ThePrint",
      title: "Sparks fly as Lok Sabha takes up Oppn resolution to remove Speaker Om Birla — who said what (Gogoi, Rijiju, Art. 95(2), 50-MP support)",
      url: "https://theprint.in/politics/sparks-fly-as-lok-sabha-takes-up-oppn-resolution-to-remove-speaker-om-birla-in-rare-move-who-said-what/2874816/",
      accessedOn: "28 August 2026",
    },
    wireSafeguarding: {
      label: "wireSafeguarding",
      publisher: "The Wire",
      title: "'Safeguarding Constitution': Opposition Brings No Confidence Motion Against Speaker Om Birla (118 MPs, 4th instance since 1954, no Deputy Speaker)",
      url: "https://m.thewire.in/article/politics/safeguarding-constitution-opposition-brings-no-confidence-motion-against-lok-sabha-speaker-om-birla",
      accessedOn: "28 August 2026",
    },
    akashvaniProd: {
      label: "akashvaniProd",
      publisher: "Akashvani (All India Radio) — News on AIR",
      title: "Lok Sabha rejects Opposition's resolution seeking removal of Speaker Om Birla with a voice vote (productivity 118%, time-share, regional languages, Shah remarks)",
      url: "https://newsonair.gov.in/lok-sabha-resumes-discussion-on-motion-to-remove-speaker-om-birla/",
      accessedOn: "28 August 2026",
    },
    businessTodayExplain: {
      label: "businessTodayExplain",
      publisher: "Business Today",
      title: "Explained: The controversy behind the move to remove Lok Sabha Speaker Om Birla (concrete-information claim about women MPs/PM chair, black-spot remark)",
      url: "https://www.businesstoday.in/india/story/explained-the-controversy-behind-the-move-to-remove-lok-sabha-speaker-om-birla-515225-2026-02-09",
      accessedOn: "28 August 2026",
    },
    timesofindia: {
      label: "timesofindia",
      publisher: "The Times of India (generic)",
      title: "Om Birla — coverage via ToI (used for parliamentary context)",
      url: "https://timesofindia.indiatimes.com/india/who-is-om-birla-the-re-elected-speaker-of-lok-sabha/articleshow/111289745.cms",
      accessedOn: "28 August 2026",
    },
  },
  lastVerified: "28 August 2026",
  disclaimer:
    "This profile aggregates role-relevant public facts about a constitutional officeholder from official rosters (Lok Sabha Secretariat / Digital Sansad, Parliament of India) and reputable secondary summaries for context. Secondary details are attributed and citation-linked; where sources diverge (e.g., state BJYM dates, child count, cooperative titles), the variation is noted rather than silently resolved. No private contact, address, or identifier is published. For authoritative current status, refer to the official roster at sansad.in/ls/members and the Speaker's page.",
};
