import type { AmitShahProfile } from "./types";

export const AMIT_SHAH_PROFILE: AmitShahProfile = {
  id: "ls-5021",
  slug: "amit-shah",
  fullName: "Amit Anilchandra Shah",
  displayName: "Amit Shah",
  alsoKnownAs: ["Shri Amit Shah", "Shah, Shri Amit", "Amit Anilchandra Shah"],
  birth: {
    date: "1964-10-22",
    displayDate: "22 October 1964",
    place: "Mumbai, Maharashtra, India (ancestral village Mansa, Gandhinagar district, Gujarat)",
    parents: {
      father: "Shri Anilchandra Shah (businessman, PVC pipes)",
      mother: "Smt. Kusumben Shah (d. 8 June 2010)",
    },
    familyBackground:
      "Born into a Gujarati Hindu Baniya (Anavil) family; great-grandfather was Nagarseth (town head) of princely Mansa (Baroda State). Lived in Mansa till age 16, schooled in Mehsana, then family shifted to Ahmedabad. Influenced by biographies of patriots, K. M. Munshi, Gandhian mother (Khadi), and the nationalist spirit of the RSS.",
  },
  personal: {
    spouse: "Smt. Sonal Shah",
    marriageYear: "1987 (widely reported; also cited as 1987 in BJP bio)",
    children: "One son — Jay Shah (BCCI Secretary, ICC Chairman); three grandchildren",
    childrenNote: "Has six sisters, two in Chicago. Avid cricket lover, reader of history/literature, trustee of Somnath Trust (since 22 Feb 2016). Languages: Hindi, Gujarati, English.",
    profession: ["Politician", "Agriculturist", "Social Worker", "Businessperson (stockbroker, cooperative banks)"],
    website: "https://www.amitshah.co.in",
    party: "Bharatiya Janata Party",
    partyAbbreviation: "BJP",
  },
  education: [
    {
      degree: "B.Sc. in Biochemistry (Second Year B.Sc. / SY B.Sc. as per affidavit)",
      institution: "C. U. Shah Science College, Ahmedabad",
      university: "Gujarat University / Ahmedabad University (reported variably; affidavit says ‘12th Pass’ as per Myneta, but Britannica/TimesNow report B.Sc. Biochemistry at CU Shah Science College)",
      year: "Studied biochemistry; worked in father's PVC business and stockbroking/cooperative banks thereafter",
      field: "Biochemistry",
    },
  ],
  officesHeld: [
    {
      office: "Member, Rashtriya Swayamsevak Sangh (RSS)",
      jurisdiction: "Ahmedabad / Gujarat",
      term: "1980 – joined RSS (age 16)",
      entryMethod: "Voluntary association",
      notes: "Entry point to Sangh parivar; inspired by RSS nationalist vision.",
    },
    {
      office: "Member, Akhil Bharatiya Vidyarthi Parishad (ABVP), Ahmedabad city unit secretary",
      jurisdiction: "Gujarat",
      term: "1982–1983 (ABVP during college; city unit secretary)",
      entryMethod: "Student wing appointment (advised by Narendra Modi, then RSS pracharak)",
    },
    {
      office: "Member, Bharatiya Janata Party (BJP); Ward Secretary → Taluka Secretary → State Secretary → Vice President → General Secretary",
      jurisdiction: "BJP, Gujarat / National",
      term: "1987 – joined BJP (one year before Modi joined BJP); BJYM activist from 1987",
      entryMethod: "Party membership; rose through BJYM/BJP hierarchy",
      notes: "Election campaign manager for L. K. Advani (Gandhinagar, 1991 Lok Sabha) and A. B. Vajpayee (Gandhinagar, 1996); campaign chief for Narendra Modi's first Assembly election (Rajkot-2, 2001). National Treasurer, BJYM (1997).",
    },
    {
      office: "State Vice-President, Gujarat BJP",
      jurisdiction: "Gujarat",
      term: "1999 – State Vice-President",
      entryMethod: "Organisational appointment",
    },
    {
      office: "State Secretary & National Treasurer, BJYM",
      jurisdiction: "Gujarat / National",
      term: "Early 1990s–1997; National Treasurer BJYM 1997",
      entryMethod: "Organisational appointment",
    },
    {
      office: "Member of Legislative Assembly, Sarkhej (by-election)",
      jurisdiction: "Gujarat Legislative Assembly",
      term: "February 1997 – 2012 (4 consecutive terms: 1997 by-poll, 1998, 2002, 2007)",
      entryMethod: "Direct election (FPTP)",
      notes:
        "1997 by-election: 76,839 votes (56.10%) — won with 24,689 margin (also reported). 1998: 1,93,373 (69.81%) margin 1,32,477 (5×). 2002: 2,88,327 (66.98%) — highest margin in Gujarat (1,58,036 reported). 2007: 4,07,659 (68.00%) — again highest margin (2,32,823). Worked as Chairman, Public Undertakings Committee.",
    },
    {
      office: "Member of Legislative Assembly, Naranpura",
      jurisdiction: "Gujarat Legislative Assembly",
      term: "2012–2017 (5th term; delimitation shift)",
      entryMethod: "Direct election",
      notes: "2012: 1,03,988 (69.19%) — margin 63,235 (constituency one-fourth size of Sarkhej). Total 5-term MLA (1997–2017).",
    },
    {
      office: "Minister of State for Home, Law & Justice, Prison, Border Security, Civil Defence, Excise, Home Guards, Transport, Prohibition, Gram Rakshak Dal, Police Housing, Legislative & Parliamentary Affairs (up to 12 portfolios)",
      jurisdiction: "Government of Gujarat (Modi ministry)",
      term: "2002–2010 (two terms; youngest minister in Modi govt in 2002)",
      entryMethod: "Appointed by CM Narendra Modi; resigned 2010 after CBI arrest in Sohrabuddin case",
      notes: "Also handled Police Housing, Border Security, Civil Defence, Gram Rakshak Dal, Prohibition, etc. Displayed ‘law & order’ push; policing reforms later cited as model.",
    },
    {
      office: "National General Secretary, BJP; In-charge of Uttar Pradesh",
      jurisdiction: "BJP, National",
      term: "2013 – National General Secretary and UP in-charge",
      entryMethod: "Organisational appointment by BJP parliamentary board",
      notes: "Led UP campaign: NDA won 73/80 seats in 2014 Lok Sabha — decisive for BJP's 282-seat national victory.",
    },
    {
      office: "President, Bharatiya Janata Party (10th President)",
      jurisdiction: "BJP, National; Chairman, NDA since 2014",
      term: "July 2014 – January 2020 (first term Jul 2014–Jan 2016, re-elected 24 Jan 2016 unanimously)",
      entryMethod: "Unanimous election by BJP central parliamentary board; youngest President at 49",
      notes:
        "Membership drive to 10 crore → BJP became world's largest party (Mar 2015: 100 million). Led BJP to victories in Maharashtra, Haryana, J&K, Jharkhand, Assam, UP, Uttarakhand, Tripura, Himachal, etc.; Mission 300 Par — 303 seats in 2019 (toured 312 constituencies, 161 public meetings, 1,500 BJP meetings).",
    },
    {
      office: "Member of Parliament, Rajya Sabha, Gujarat",
      jurisdiction: "Parliament of India — Council of States",
      term: "19 August 2017 – 29 May 2019 (resigned on election to Lok Sabha)",
      entryMethod: "Indirect election (elected by Gujarat Legislative Assembly)",
      notes: "First entry to Parliament via Upper House.",
    },
    {
      office: "Member of Parliament, Lok Sabha, Gandhinagar",
      jurisdiction: "Parliament of India — House of the People (543 seats)",
      term: "17th Lok Sabha (2019–2024) and 18th Lok Sabha (2024–present)",
      entryMethod: "Direct election (FPTP)",
      predecessor: "L. K. Advani (former) / seat held by BJP veterans Vajpayee, Advani",
      notes: "2019: 8,88,210 votes (69.76%) — margin 5,57,014 vs C. J. Chavda (INC). 2024: 10,10,972 (76.5%) — margin 7,44,716 vs Sonal Patel (INC) (also reported). Seat previously held by Advani/Vajpayee.",
    },
    {
      office: "Union Cabinet Minister — Minister of Home Affairs (31st/32nd; longest-serving)",
      jurisdiction: "Government of India — Ministry of Home Affairs",
      term: "30 May 2019 (oath) → 1 June 2019 (charge) – present (through Modi 2.0 and 3.0, sworn again 9 June 2024, second after Rajnath Singh)",
      entryMethod: "Appointed by President on advice of Prime Minister under Constitution Art.75",
      notes: "Also member, Cabinet Committee on Security. Historic decisions: Article 370 abrogation 5 Aug 2019, CAA 2019, new criminal codes 2024.",
    },
    {
      office: "Union Cabinet Minister — Minister of Cooperation (1st Minister of Cooperation, new ministry)",
      jurisdiction: "Government of India — Ministry of Cooperation",
      term: "7 July 2021 – present (concurrently with Home)",
      entryMethod: "Additional portfolio allocated by President on PM's advice (Cabinet reshuffle)",
      notes: "First to hold the newly created Cooperation portfolio; cooperative reforms and cooperative-bank strengthening.",
    },
  ],
  timeline: [
    {
      date: "1964-10-22",
      dateLabel: "22 October 1964",
      title: "Born in Mumbai (Mansa ancestral)",
      description:
        "Born to Anilchandra Shah (PVC pipe business) and Kusumben Shah in Mumbai; ancestral home Mansa (Gandhinagar, Baroda/Princely Mansa, Nagarseth lineage). Childhood in Mansa till age 16, schooled in Mehsana.",
      category: "birth",
      citationIds: ["wiki", "britannica", "bjpBio", "mhaBio"],
    },
    {
      date: "1980",
      dateLabel: "1980 · Age 16",
      title: "Joined RSS",
      description:
        "Became an active RSS member in Ahmedabad; moved from Mansa schooling to Ahmedabad after 16. Inspired by patriot biographies, K. M. Munshi, and mother's Gandhian Khadi influence.",
      category: "youth",
      citationIds: ["wiki", "bjpBio", "amitshahSite"],
    },
    {
      date: "1982-1983",
      dateLabel: "1982–1983",
      title: "ABVP — college politics",
      description:
        "During B.Sc. Biochemistry at CU Shah Science College, joined Akhil Bharatiya Vidyarthi Parishad (RSS student wing); became Ahmedabad city unit secretary at ~18. Unlike many ABVP leaders, moved early to BJP youth wing.",
      category: "youth",
      citationIds: ["wiki", "britannica", "bjpBio"],
    },
    {
      date: "1987",
      dateLabel: "1987",
      title: "Joined BJP (and BJYM)",
      description:
        "Member, Bharatiya Janata Yuva Morcha (BJYM) from 1987 — one year before Modi joined BJP. Became BJYM activist (ward → taluka → state secretary → vice-president → general secretary). Also helped run father's business and worked as stockbroker/cooperative banks.",
      category: "youth",
      citationIds: ["wiki", "britannica", "bjpBio"],
    },
    {
      date: "1991",
      dateLabel: "1991",
      title: "First national campaign — Advani, Gandhinagar",
      description:
        "Election campaign manager for L. K. Advani in Gandhinagar (1991 Lok Sabha) — first exposure to national-level booth management. Repeated for Vajpayee (Gandhinagar, 1996).",
      category: "youth",
      citationIds: ["wiki", "mhaBio", "censusBio"],
    },
    {
      date: "1997-02",
      dateLabel: "February 1997",
      title: "First MLA — Sarkhej by-election",
      description:
        "Modi lobbied for Shah's ticket; won Sarkhej by-election with 76,839 votes (56.10%, margin ~24,689). Retained in 1998 (1,93,373, 69.81%). Began 5-term MLA run.",
      category: "assembly",
      citationIds: ["wiki", "amitshahSite", "mhaBio"],
    },
    {
      date: "1999",
      dateLabel: "1999",
      title: "State Vice-President, Gujarat BJP",
      description: "Appointed State Vice-President, Gujarat BJP — organisational rise within state unit.",
      category: "party",
      citationIds: ["amitshahSite", "bjpBio"],
    },
    {
      date: "2002",
      dateLabel: "2002",
      title: "Youngest Gujarat Minister + record MLA win",
      description:
        "Won Sarkhej 2002 with 2,88,327 votes (66.98%) — highest margin statewide (≈1,58,036). Sworn as MoS for Home and 11 other portfolios (Law & Justice, Prison, Border Security, Civil Defence, Excise, Transport, Prohibition, Home Guards, Gram Rakshak Dal, Police Housing, Legislative & Parliamentary Affairs) — youngest in Modi's council.",
      category: "minister",
      citationIds: ["wiki", "amitshahSite", "censusBio"],
    },
    {
      date: "2007",
      dateLabel: "2007",
      title: "Fourth term, again highest margin",
      description: "Won Sarkhej again with 4,07,659 (68.00%) — again highest margin (≈2,32,823). Consolidated as Modi's closest aide in Gandhinagar.",
      category: "assembly",
      citationIds: ["wiki", "amitshahSite"],
    },
    {
      date: "2010-07",
      dateLabel: "July 2010 – Oct 2010",
      title: "Arrested in Sohrabuddin case; resigned as minister",
      description:
        "Arrested by CBI on 25 Jul 2010 in the 2005 Sohrabuddin Sheikh / 2006 Tulsiram Prajapati alleged fake-encounter cases (charged with murder/kidnapping). Resigned as minister. Granted bail 29 Oct 2010 after 3+ months in jail; externed from Gujarat by Supreme Court (transferred trial to Mumbai 2012).",
      category: "assembly",
      citationIds: ["wiki", "indianExpressSohrabuddin", "bbcSohrabuddin"],
    },
    {
      date: "2012",
      dateLabel: "2012",
      title: "Fifth Assembly term — Naranpura (after delimitation)",
      description: "Won Naranpura with 1,03,988 (69.19%) after Sarkhej delimitation. Continued as MLA despite legal proceedings.",
      category: "assembly",
      citationIds: ["wiki", "amitshahSite"],
    },
    {
      date: "2013",
      dateLabel: "2013",
      title: "National General Secretary + UP in-charge",
      description: "Appointed National General Secretary, BJP and in-charge of politically decisive Uttar Pradesh — meticulous booth work that delivered NDA 73/80 in 2014.",
      category: "party",
      citationIds: ["wiki", "mhaBio"],
    },
    {
      date: "2014-07",
      dateLabel: "July 2014",
      title: "BJP National President — youngest at 49",
      description:
        "Unanimously approved as 10th BJP President (central parliamentary board), re-elected 24 Jan 2016 unanimously. Membership drive to 10 crore — world's largest party (Mar 2015). Led BJP to wins in Maharashtra, Haryana, J&K, Jharkhand, Assam etc.",
      category: "party",
      citationIds: ["wiki", "bjpBio", "amitshahSite"],
    },
    {
      date: "2014-12-30",
      dateLabel: "30–31 December 2014",
      title: "Discharged in Sohrabuddin case — clean chit",
      description:
        "Special CBI Court, Mumbai (Judge M. B. Gosavi) discharged Shah (Accused No.16), holding CBI hearsay evidence insufficient, call records (38 with Vanzara, 343 with Pandian) explained as home-minister's official duty, and inference ‘for political reasons’. CBI did not appeal; discharge challenge by Rubabuddin withdrawn; activist Harsh Mander's plea to reopen dismissed by Supreme Court (1 Aug 2016) for lack of locus.",
      category: "assembly",
      citationIds: ["indianExpressSohrabuddin", "bbcSohrabuddin", "supremeCourtReject", "timesOfIndiaIshrat"],
    },
    {
      date: "2017-08-19",
      dateLabel: "19 August 2017 – 29 May 2019",
      title: "Rajya Sabha — Gujarat",
      description: "Elected to Rajya Sabha from Gujarat — first entry to Parliament via Upper House.",
      category: "parliament",
      citationIds: ["wiki", "amitshahSite"],
    },
    {
      date: "2019-05-23",
      dateLabel: "May 2019",
      title: "Elected to 17th Lok Sabha — Gandhinagar",
      description: "Won Gandhinagar with 8,88,210 votes (69.76%, margin 5,57,014 vs C. J. Chavda, INC). Also won ‘Mission 300 Par’ as BJP President — BJP 303 seats.",
      category: "parliament",
      citationIds: ["wiki", "pibShahAssume", "theHinduBusinessLine2024"],
    },
    {
      date: "2019-05-30",
      dateLabel: "30 May 2019 → 1 June 2019",
      title: "Sworn as Union Home Minister",
      description: "Took oath as Cabinet Minister 30 May 2019, assumed office as Home Minister 1 June 2019 (North Block, greeted by Home Secretary Rajiv Gauba) — 31st/35th Home Minister (count varies), also on Cabinet Committee on Security.",
      category: "minister",
      citationIds: ["pibShahAssume", "bjpBio", "ramnath301"],
    },
    {
      date: "2019-08-05",
      dateLabel: "5–6 August 2019",
      title: "Abrogation of Article 370",
      description:
        "Moved the Jammu & Kashmir Reorganisation Bill / Presidential order reading down Art.370 and splitting the state into UTs of J&K and Ladakh in Rajya Sabha (125–61) and Lok Sabha (370–70). Operation All-Out backstory, secrecy, extended Parliament session, heavy security deployment, NSA Doval/RAW coordination, communication shutdown. Supreme Court upheld 11 Dec 2023 (PIB). Defining stroke of his national career (Indian Express/FP/PIB).",
      category: "minister",
      citationIds: ["wiki", "indianExpressArt370", "firstpostArt370", "pibArt370", "britannica"],
    },
    {
      date: "2019-12",
      dateLabel: "December 2019",
      title: "Citizenship (Amendment) Act, 2019 — piloted as Home Minister",
      description:
        "Parliament enacted CAA (persecuted Hindu/Sikh/Buddhist/Jain/Christian/Parsi from Pakistan/Bangladesh/Afghanistan pre-Dec 2014). Shah's ‘chronology’ — ‘First CAB, then NRC’ (1 May 2019 tweet, scroll.in 5× compilation) — became central to later protests. Rules notified before 2024 Lok Sabha polls; Shah: ‘CAA will never be taken back, sovereign decision’.",
      category: "minister",
      citationIds: ["scrollCAA", "wireCAAdodge", "outlookCAA", "theHinduCAA"],
    },
    {
      date: "2021-07-07",
      dateLabel: "7 July 2021 – present",
      title: "First Minister of Cooperation (concurrently Home)",
      description: "Portfolio allocated in 2021 reshuffle — first to hold newly created Cooperation ministry; cooperative-sector/bank reforms.",
      category: "minister",
      citationIds: ["wiki", "timesNowArt370"],
    },
    {
      date: "2024-05-07",
      dateLabel: "May 2024",
      title: "Re-elected to 18th Lok Sabha — Gandhinagar (record margin)",
      description: "Won Gandhinagar with 10,10,972 votes (76.5%) — margin 7,44,716 vs Sonal Patel (INC), second consecutive Lok Sabha term. Sworn again 9 June 2024 (second after Rajnath Singh) in Modi 3.0; retains Home + Cooperation.",
      category: "parliament",
      citationIds: ["wiki", "theHinduBusinessLine2024"],
    },
    {
      date: "2024-07-01",
      dateLabel: "1 July 2024",
      title: "New criminal codes — Bharatiya Nyaya Sanhita etc.",
      description: "Piloted three laws replacing IPC/CrPC/Evidence Act (1860/1972): Bharatiya Nyaya Sanhita, Bharatiya Nagarik Suraksha Sanhita, Bharatiya Sakshya Adhiniyam — into force 1 Jul 2024 (Times Now longest-serving Home Minister note).",
      category: "minister",
      citationIds: ["timesNowArt370"],
    },
    {
      date: "2025-08-06",
      dateLabel: "August 2025 (reported)",
      title: "Longest-serving Union Home Minister — 6+ years",
      description: "Times Now reports Shah as longest-serving Home Minister (overtaking L. K. Advani/others) — continuous since 1 Jun 2019.",
      category: "minister",
      citationIds: ["timesNowArt370"],
    },
  ],
  socialInitiatives: [
    {
      name: "Public Undertakings Committee — Gujarat Assembly",
      since: "As MLA (late 1990s–2000s)",
      description: "Chairman, Public Undertakings Committee — scrutiny of state PSUs, as part of his legislative committee work.",
      citationIds: ["censusBio"],
    },
    {
      name: "Cooperative-sector modernisation (ADC Bank, Gujarat)",
      since: "1990s–2000s",
      description: "Worked as stockbroker and in Ahmed District Cooperative Bank / Ahmedabad District Cooperative Bank revival; financial inclusion and cooperative-bank governance — precursor to national Cooperation ministry.",
      citationIds: ["wiki", "mhaBio"],
    },
    {
      name: "AUDA / Urban development funding for Sarkhej–Gandhinagar belt",
      since: "1997–2012 (as MLA)",
      description:
        "Despite meagre MLA grant, mobilised thousands of crores from Ahmedabad Urban Development Authority (AUDA), state government and Centre for roads, drainage, water and urban expansion in his constituencies.",
      citationIds: ["amitshahSite"],
    },
    {
      name: "Somnath Trust — religious/cultural trusteeship",
      since: "22 Feb 2016 – trustee",
      description: "Trustee of Shree Somnath Trust, Gujarat — restoration and cultural-heritage work at Somnath Jyotirlinga.",
      citationIds: ["mhaBio"],
    },
    {
      name: "Sports & youth — Gujarat Cricket Association",
      since: "2014–2019",
      description: "President, Gujarat Cricket Association; avid cricket lover and sports patron — later family association via son Jay Shah's BCCI/ICC roles.",
      citationIds: ["britannica", "wiki"],
    },
  ],
  ministerial: {
    portfolios: ["Minister of Home Affairs", "Minister of Cooperation"],
    firstOath: "30 May 2019 (assumed 1 June 2019) — retained 9 June 2024 (Modi 3.0)",
    historicNotes: [
      "31st/32nd Home Minister (count varies by list) — longest-serving (6+ years from 1 Jun 2019, Times Now Aug 2025)",
      "1st Minister of Cooperation — first to hold the newly created ministry (7 Jul 2021)",
      "10th BJP National President — youngest at 49 (Jul 2014), re-elected 24 Jan 2016 unanimously; also Chairman, NDA since 2014",
      "5-term Gujarat MLA (1997–2017) — Sarkhej ×4 (highest statewide margins) → Naranpura ×1 after delimitation",
      "Only post-2014 BJP President to deliver 282 (2014) and 303 (2019) Lok Sabha majorities — ‘Mission 300 Par’ architect",
    ],
    reforms: [
      "Abrogation of Article 370 (J&K Reorganisation) — 5 Aug 2019 (RS 125–61) / 6 Aug 2019 (LS 370–70) — and creation of UTs J&K + Ladakh; Supreme Court upheld 11 Dec 2023",
      "New criminal codes replacing IPC/CrPC/Evidence — Bharatiya Nyaya Sanhita, Bharatiya Nagarik Suraksha Sanhita, Bharatiya Sakshya Adhiniyam (into force 1 Jul 2024)",
      "FCRA regulation, NIA/UAPA strengthening, CAPF modernisation, and internal-security coordination",
    ],
    majorDecisions: [
      "CAA 2019 — citizenship for persecuted non-Muslim minorities from Pakistan/Bangladesh/Afghanistan (cutoff 31 Dec 2014); rules notified pre-2024 polls; central to CAA-NRC chronology debate",
      "J&K statehood reorganisation, delimitation, and heavy security-management (Doval/RAW/PMO coordination, communication shutdown, satellite phones/NTRO Heron drones per FP/Express)",
      "Cooperative-sector ministry creation and cooperative-bank reforms; election-security management as strategist-in-chief",
    ],
    criticisms: [
      "Article 370 passage & Valley lockdown (communication blackout, detentions) — praised as decisive, criticised by opposition/rights groups as heavy-handed",
      "CAA-NRC ‘chronology’ (1 May 2019: ‘First CAB, then NRC … detect and deport every infiltrator’) — later deflected as ‘talk only CAA’ (Wire 14 Mar 2024); protests saw 100+ deaths (Hindu reporting)",
      "NRC exercise flaws (Assam 19 lakh excluded) and national-NRC promise vs. later denial of link",
    ],
  },
  salaries: [
    {
      office: "RSS Volunteer / ABVP Ahmedabad city unit secretary",
      period: "1980–1983",
      salary: "No salary — voluntary student movement",
      allowances: "—",
      totalApprox: "Unpaid honorary",
      legalBasis: "Voluntary student organisation",
      citationIds: ["wiki", "bjpBio"],
    },
    {
      office: "BJP / BJYM organiser (Ward → Taluka → State Secretary → Vice President → General Secretary)",
      period: "1987–1997",
      salary: "No salary — party organisational post",
      allowances: "Organisational support only",
      totalApprox: "Unpaid (honorary party work)",
      legalBasis: "BJP organisational appointment",
      citationIds: ["wiki", "censusBio"],
    },
    {
      office: "Member of Legislative Assembly, Sarkhej / Naranpura (Gujarat)",
      period: "Feb 1997 – Aug 2017 (5 terms)",
      salary: "Basic ₹40,000 pm from 1 Apr 2019 under Gujarat / analogous Rajasthan pattern (Rajasthan Act 1956 §4 as illustrative; Gujarat scale closely comparable)",
      allowances: "Daily ₹2,000/₹2,500, vehicle ₹30k, sumptuary ₹45k, secretarial ₹30k, travel ₹2L p.a., plus free housing/medical — as per state legislature Act",
      totalApprox: "~₹1.47 lakh pm with allowances (2025 illustrative Rajasthan; Gujarat comparable). 1997–2012 basic was lower (≈₹15k–₹25k era).",
      legalBasis: "Gujarat Legislative Assembly Officers & Members Act (pattern as Rajasthan Act 1956 §§4,8); Bhaskar 23 Jul 2025; Acadlog MLA compilation",
      notes: "Salary revisions periodic by state Act; current illustrative total uses 2019–2025 rates.",
      citationIds: ["rajasthanAct", "bhaskarRajasthan", "acadlogMLA"],
    },
    {
      office: "Minister of State for Home etc. (Gujarat) — up to 12 portfolios",
      period: "2002–2010",
      salary: "Pay & allowances equivalent to Minister of State, Gujarat (in addition to MLA salary per prevailing rules)",
      allowances: "Ministerial perks: staff, vehicle, residence as per MoS entitlement",
      totalApprox: "At state MoS scale — addition to MLA pay per GoG notification",
      legalBasis: "Gujarat Ministers Act; appointment at MoS rank by CM",
      notes: "Resigned Jul 2010 after CBI charges; bail Oct 2010.",
      citationIds: ["wiki", "censusBio"],
    },
    {
      office: "President, BJP (National President) + Chairman, NDA",
      period: "Jul 2014 – Jan 2020",
      salary: "No legislative salary — full-time party post (party-paid, not exchequer); no MP salary in this period until 2017",
      allowances: "Party support only until Rajya Sabha salary began",
      totalApprox: "Full-time party organisational (non-governmental)",
      legalBasis: "BJP organisational appointment",
      citationIds: ["wiki", "bjpBio"],
    },
    {
      office: "Member of Parliament, Rajya Sabha, Gujarat",
      period: "19 Aug 2017 – 29 May 2019",
      salary: "₹1,00,000 pm (1 Apr 2018–31 Mar 2023) → ₹1,24,000 pm (from 1 Apr 2023, notified 24 Mar 2025, G.S.R.188(E))",
      allowances: "Constituency ₹70k→₹87k + Office ₹60k→₹70k + Daily ₹2,000→₹2,500 per sitting day + furniture; plus air/rail/medical/housing",
      totalApprox: "Assured cash ≈₹2.30L pm (pre-2023) → ₹2.81L pm (post-Apr 2023 excl. daily)",
      legalBasis: "Salary, Allowances and Pension of Members of Parliament Act, 1954 §§3, 8A (Finance Act 2018 auto-index); G.S.R.188(E) 24 Mar 2025; BS 24 Mar 2025",
      citationIds: ["mpSalaryGazette", "theHinduSalary", "bsSalary", "etSalary"],
    },
    {
      office: "Member of Parliament, Lok Sabha, Gandhinagar (17th/18th)",
      period: "2019–present (elected May 2019, May 2024)",
      salary: "Same MP scale: ₹1,24,000 pm salary (from 1 Apr 2023) + allowances as above",
      allowances: "Constituency ₹87k + Office ₹70k + Daily ₹2,500 per sitting day + furniture ₹1.25L one-time; 34 flights, unlimited 1st-class rail, medical, housing",
      totalApprox: "~₹2.81 lakh pm assured cash excl. daily (2023+ scale)",
      legalBasis: "MP Act 1954 as amended; G.S.R.188(E); Economic Times/BS calculations",
      citationIds: ["mpSalaryGazette", "etSalary", "bsSalary"],
    },
    {
      office: "Union Cabinet Minister — Home Affairs + Cooperation",
      period: "30 May 2019 – present (re-sworn 9 Jun 2024)",
      salary: "Same as MP salary (Cabinet Minister salary is pegged to MP salary under Officers Salaries Act 1953, Art.97) — plus Cabinet perks",
      allowances: "Sumptuary ₹3,000 pm (Cabinet), free furnished residence (New Delhi), staff, travel, medical — plus MP allowances continue",
      totalApprox: "Cabinet scale: MP assured cash (~₹2.81L) + sumptuary/residence/staff; no separate ‘Home Minister salary’ figure published — governed by Officers/Salaries Act",
      legalBasis: "Constitution Art.97 + Salaries and Allowances of Officers of Parliament Act 1953 (§§3–5) + Salaries and Allowances of Ministers Act; Second Schedule fallback; MPA NeVA amenities sheet",
      notes: "Is longest-serving Home Minister (6+ years).",
      citationIds: ["officersParliamentAct", "article97", "nevaAmenities"],
    },
  ],
  netWorthTimeline: [
    {
      election: "Gujarat Assembly 2007 — Sarkhej",
      year: "2007",
      totalAssets: "₹5,57,23,561 (~₹5.57 Cr)",
      movable: "~₹? (comparable; affidavit on Myneta)",
      immovable: "~₹? (comparable)",
      liabilities: "₹19,66,867 (~₹19.66 lakh)",
      cases: "0 (per 2007 affidavit on compare)",
      citationIds: ["mynetaCompareShah"],
    },
    {
      election: "Gujarat Assembly 2012 — Naranpura",
      year: "2012",
      totalAssets: "₹11,77,68,785 (~₹11.77 Cr)",
      movable: "~₹? (comparable)",
      immovable: "~₹? (comparable)",
      liabilities: "~₹? (see compare)",
      cases: "2 (per compare)",
      citationIds: ["mynetaCompareShah"],
    },
    {
      election: "Lok Sabha 2019 — Gandhinagar (Winner)",
      year: "2019",
      totalAssets: "₹40,32,75,307 (~₹40.32 Cr) — self movable ₹18.24 Cr + immovable ₹12.87 Cr; spouse movable ₹5.30 Cr + immovable ₹3.90 Cr",
      movable: "₹23,55,26,476 (~₹23.55 Cr) incl. shares ₹14.64 Cr inherited listed, bank ~₹18.8 lakh, precious metals ~₹72.87 lakh, no vehicle disclosed",
      immovable: "₹16,77,48,831 (~₹16.77 Cr) incl. 11.885 acres Karbatiya (Vadnagar), 6.26 Cr Shilaj non-agri land (inherited), commercial Ashram Road ₹1.5 Cr, Mansa house ₹2.5 lakh, Thaltej bungalow ₹1.5 Cr",
      liabilities: "₹47,69,587 (~₹47.69 lakh) — loans (self ₹15.77L, spouse ₹31.92L)",
      cases: "4 (per 2019 affidavit/compare; also reported as 4 cases, 3 serious by Hindu 2024 — but Myneta 2019 detail shows 4)",
      incomeSelf: "₹53,90,970 p.a. (2017-18 ITR; was ₹41,93,218 in 2013-14)",
      incomeSpouse: "Included in joint; wife also has ₹8.35 Cr assets",
      citationIds: ["myneta2019Shah", "mynetaCompareShah", "toIAmitAsset19", "myneta2024Shah"],
    },
    {
      election: "Lok Sabha 2024 — Gandhinagar (Winner)",
      year: "2024",
      totalAssets: "₹65,67,12,498 (~₹65.67 Cr) — +63% over 2019 (₹40.32→₹65.67 Cr); also reported +100%+ (₹30.49→₹65.67 Cr by banded market-value change in 2019 filing method)",
      movable: "₹42,80,25,833 (~₹42.80 Cr) incl. shares ~₹17.46 Cr, stock ~₹? FDs ADC Bank ₹? + Kotak ~₹77.9 lakh + cash, bank ₹3.03 Cr, wife ₹22.46 Cr + gold/silver ~₹1.10 Cr",
      immovable: "₹22,86,86,665 (~₹22.86 Cr) incl. agri, Shilaj 49,461 sq ft ₹6 Cr, Mansa plots, lilapur, Vadnagar etc.; wife immovable ₹6.55 Cr+",
      liabilities: "₹42,09,587 (~₹42.09 lakh)",
      cases: "3 (per 2024 compare: 3 cases, 3 serious by Hindu) — down from 4 in 2019 (affidavit 2024 shows 3 pending, all serious)",
      incomeSelf: "₹1.1 Crore p.a. declared (Hindu 2024)",
      incomeSpouse: "Included in spouse ₹22.46 Cr movable; separate 2024 income ~₹? (see myneta)",
      citationIds: ["myneta2024Shah", "mynetaCompareShah", "etAmitAsset24", "theHinduAmitBio", "mynetaCompAmit"],
    },
  ],
  netWorthNotes: [
    "All figures self-declared in ECI affidavits, banded by Myneta/ADR. Market-value rule for immovable (vs pure purchase value in older filings) inflates 2019→2024 immovable comparison — 2019 filing also introduced market-value declaration (ToI 31 Mar 2019).",
    "Movable jump 2019→2024 is largely inherited shares/mutual-funds list (annexure A2, Scribd PDF): long tail of listed holdings (e.g., Bharti Airtel ₹1.72 Cr, Aditya Birla Fashion ₹45.99 lakh, many micro-holdings) plus bank FDs at ADC/Kotak/HDFC.",
    "Immovable includes inherited Shilaj non-agri land ₹6 Cr (inherited), Karbatiya 11.885 acres (Vadnagar, 40% joint with wife), Lilapur agri, and Thaltej/Ashram Road bungalows/commercial. No government house counted — ministerial residence is not an asset.",
    "Liabilities declined modestly ₹47.69L→₹42.09L (loans from persons). Cases: counted as ‘Total Criminal Cases’ in affidavit header — not convictions; nature below in §10.",
    "No vehicle was disclosed in 2024 (and 2019: ‘does not own any vehicle’ per ToI) — consistent across both filings.",
  ],
  workHighlights: [
    {
      title: "Abrogation of Article 370 — J&K Reorganisation (UTs J&K + Ladakh)",
      date: "5–6 Aug 2019; upheld 11 Dec 2023",
      kind: "positive",
      summary: "As Home Minister, moved the resolution/Bill to read down Art.370 and split the state (RS 125–61, LS 370–70); defining stroke, executed with secrecy, Doval/Mehta/RAW coordination, heavy security, extended session. Supreme Court later upheld.",
      sourceLabel: "PIB / Indian Express / Firstpost / Wikipedia",
      citationId: "pibArt370",
    },
    {
      title: "New criminal codes — Bharatiya Nyaya Sanhita, etc.",
      date: "1 Jul 2024 into force",
      kind: "positive",
      summary: "Piloted three laws replacing IPC (1860)/CrPC/Evidence Act (1872) — Bharatiya Nyaya Sanhita, Bharatiya Nagarik Suraksha Sanhita, Bharatiya Sakshya Adhiniyam — longest-serving Home Minister milestone.",
      sourceLabel: "Times Now",
      citationId: "timesNowArt370",
    },
    {
      title: "CAA 2019 — enacted as Home Minister",
      date: "Dec 2019; rules notified pre-2024 polls",
      kind: "mixed",
      summary: "CAA gave citizenship to persecuted Hindu/Sikh/Buddhist/Jain/Christian/Parsi from Pakistan/Bangladesh/Afghanistan (pre-31 Dec 2014). Shah: ‘CAA will never be taken back, sovereign decision’ (Outlook 14 Mar 2024; Hindu 10 Feb 2024). Government claims no Indian loses citizenship; opposition cites religious test + timing.",
      sourceLabel: "Outlook / The Hindu",
      citationId: "outlookCAA",
    },
    {
      title: "BJP expansion — world's largest party & 2019 majority",
      date: "2014–2020 as President",
      kind: "positive",
      summary: "Membership drive to 10 crore (world's largest, Mar 2015); UP 73/80 in 2014, 303 seats in 2019 (Mission 300 Par — toured 312 seats, 161 meets, 1,500 BJP meets).",
      sourceLabel: "BJP / Wikipedia / MHA bio",
      citationId: "bjpBio",
    },
    {
      title: "Cooperation ministry — first holder & cooperative-bank revival",
      date: "7 Jul 2021–present",
      kind: "positive",
      summary: "First Minister of Cooperation (new ministry); cooperative-sector/bank strengthening, ADC Bank reform narrative.",
      sourceLabel: "Wikipedia",
      citationId: "wiki",
    },
    {
      title: "CAA-NRC ‘chronology’ — ‘First CAB, then NRC’ and later deflections",
      date: "1 May 2019 tweet → 14 Mar 2024 ‘talk only CAA’",
      kind: "critical",
      summary: "Shah's 2019 ‘chronology’ (‘First CAB … then NRC … detect and deport every infiltrator’) was repeatedly cited by protesters (Scroll 20 Dec 2019, 5× compilation). Later, as rules neared elections, Shah dodged chronology: ‘There is no NRC now, talk only about CAA’ (Wire 14 Mar 2024). Government later said CAA ≠ NRC.",
      sourceLabel: "Scroll / The Wire",
      citationId: "scrollCAA",
    },
    {
      title: "NRC Assam — 19 lakh excluded, BJP disavowed own list",
      date: "31 Aug 2019",
      kind: "critical",
      summary: "All-India NRC promise met Assam NRC result (19 lakh left out, BJP disavowed its own exercise) — cited as evidence of bureaucratic, error-prone process (Scroll explainer).",
      sourceLabel: "Scroll",
      citationId: "scrollCAA",
    },
    {
      title: "Article 370 Valley lockdown — security success vs rights critique",
      date: "Aug 2019–2020",
      kind: "mixed",
      summary: "Heavy deployment, detentions, communication shutdown, satellite phones/NTRO drones — praised as preventing misadventure, criticised as heavy-handed; Centre told SC abrogation brought ‘peace, busting terror network, no stone-pelting’ — countered by rights and opposition critique.",
      sourceLabel: "Firstpost / Indian Express",
      citationId: "indianExpressArt370",
    },
    {
      title: "Firstpost 5-year anniversary — ‘secret exercise’ orchestration",
      date: "4 Aug 2023 retrospective",
      kind: "positive",
      summary: "Retrospective credited Shah with midnight-oil file work at Parliament office, coordination with SG Tushar Mehta and NSA Doval, whips, and full secrecy — ‘kept cards close to chest, surprised Oppn and most ministers’ (Express 5 Aug 2019).",
      sourceLabel: "Firstpost / Indian Express",
      citationId: "firstpostArt370",
    },
  ],
  allegations: [
    {
      title: "Sohrabuddin Sheikh / Tulsiram Prajapati / Kauser Bi alleged fake encounters — arrested, then discharged/acquitted",
      date: "2005–2006 alleged acts; FIR 2010; discharge 30–31 Dec 2014; no appeal by CBI; Mander plea dismissed 1 Aug 2016; 2018 acquittal of 22; HC upheld 8 May 2026",
      allegation: "As Gujarat Home Minister (2002–2010), alleged conspiracy, murder, kidnapping and abduction in the 26 Nov 2005 alleged fake encounter of Sohrabuddin Sheikh (+ wife Kauser Bi, abducted Hyderabad→Sangli, killed near Gandhinagar) and 28 Dec 2006 alleged fake encounter of eyewitness Tulsiram Prajapati (Chapri, Banaskantha). CBI case: Shah in constant contact via call data (38 calls with D.G. Vanzara, 343 with Rajkumar Pandian) around encounters.",
      context: "State ATS/CID probed; SC transferred probe to CBI (2010) and trial to Mumbai (2012). Shah arrested 25 Jul 2010 (Accused No.16), spent 3+ months jail, bailed 29 Oct 2010, externed from Gujarat. 38 accused total, including senior IPS Dinesh M.N., Pandiyan, Vanzara, ex-Rajasthan HM Gulab Chand Kataria.",
      responseOrStatus: "Shah: falsely implicated for political reasons by Congress/CBI; calls were official home-minister duty (ATS anti-terror). Defence: CBI ‘mischievously’ clubbed Sohrabuddin with Prajapati eyewitness, picked selective call records without content, relied on hearsay (complainant Rubabuddin, Naimuddin). Sought discharge.",
      outcome: "Discharged by Special CBI Court, Mumbai (Judge M. B. Gosavi, 31 Dec 2014): ‘inference not acceptable … not sufficient to proceed … apparently shown to be involved for political reasons.’ CBI did not appeal; Sohrabuddin's brother Rubabuddin withdrew HC challenge. Activist Harsh Mander's plea to reopen — dismissed by Supreme Court (Justice S. A. Bobde & Ashok Bhushan, 1 Aug 2016): ‘cannot be interminably prosecuted’, no locus. Special Court (Judge S.J. Sharma, 21 Dec 2018) acquitted remaining 22 accused (CBI ‘premeditated theory … implicate political leaders’, ~92 of 200 witnesses hostile, CrPC §197 sanction missing). Bombay HC upheld acquittal 8 May 2026 (CJ Shree Chandrashekhar & Justice Ankhad): ‘meritless’ appeals dismissed. BBC called it major reprieve for Modi's closest confidant.",
      citationIds: ["indianExpressSohrabuddin", "bbcSohrabuddin", "supremeCourtReject", "timesOfIndiaSohrabuddin", "indianExpressExplain", "bbcAcquittal"],
    },
    {
      title: "Ishrat Jahan (2004) alleged fake encounter — questioned, then no evidence / clean chit",
      date: "19-year-old + 3 killed 2004 outskirts Ahmedabad; CBI questioned Shah 2013; clean chit 7 May 2014",
      allegation: "Four killed by Gujarat police + IB claimed they were terrorists targeting CM Modi. Jailed IPS D.G. Vanzara alleged ‘conscious policy’ from Gandhinagar and that government ‘inspiring, guiding, monitoring’ encounters. PILs sought Shah as accused (Pranesh Pillai father petition).",
      context: "CBI chargesheeted 11 policemen + 4 IB officers (murder/conspiracy) — no political leader chargesheeted. Kapil Sibal raised ‘clinching evidence’ claim in April 2014 campaign.",
      responseOrStatus: "CBI counsel told Special Court 7 May 2014: ‘No sufficient evidence has been found against Amit Shah’ — evidence laid before court, no chargesheet against him. Shah had been questioned (ET 12 Oct 2013) but not chargesheeted.",
      outcome: "Clean chit — no chargesheet, no sanction for IB officers; case proceeded only against police/IB personnel. No conviction against Shah.",
      citationIds: ["timesOfIndiaIshrat", "ndtvIshrat", "economicTimesIshrat"],
    },
    {
      title: "Snoop-gate / ‘Sahiba’ surveillance allegation (2013)",
      date: "Nov 2013 (Cobrapost/Glad etc. tapes — investigative reports)",
      allegation: "Investigative portals alleged Shah, as Gujarat Home Minister, ordered illegal surveillance on a young woman architect (‘Madhuri’/‘Sahiba’) at request of ‘Saheb’ — based on purported call recordings with IPS G.L. Singhal.`",
      context: "Amplified during 2014 campaign; women’s privacy/ snooping debate. No FIR against Shah produced in retrieved reputable secondary record showing filed case; BJP called it political smear.",
      responseOrStatus: "BJP denied illegality — said surveillance at family request for security; no CBI chargesheet naming Shah in retrieved record. No court finding of guilt in compiled sources.",
      outcome: "Neutral fact: allegation was widely reported, no conviction or chargesheet against Shah found in compiled reputable sources; verify against authoritative judicial record for current status.",
      citationIds: ["wiki", "britannica"],
    },
    {
      title: "Electoral expenditure / asset-growth scrutiny — no PMLA/Lokpal FIR found",
      date: "Through 2024 affidavits",
      allegation: "Asset growth ₹11.77 Cr (2012) → ₹40.32 Cr (2019) → ₹65.67 Cr (2024) noted by press as +63% (or +100%+ on banded market-value basis); raw jump from inherited shares/land revaluation.",
      context: "Movable includes inherited listed shares (Bharti Airtel etc.), FDs; immovable includes inherited Shilaj 6 Cr + Karbatiya agri. Growth calculated by ADR/Myneta from ECI affidavits.",
      responseOrStatus: "No specific quid-pro-quo, PMLA, ED or Lokpal FIR attributed to Shah in retrieved reputable record; disclosures are ECI affidavit-based. Reported growth framed as bank/stock/valuation effect, not as filed illegality.",
      outcome: "No allegation to rebut as of last verified date — dossier will update if filed case appears.",
      citationIds: ["myneta2024Shah", "etAmitAsset24", "myneta2019Shah", "adrAmitCompare"],
    },
    {
      title: "Affidavit pending-cases count — 3 in 2024 (down from 4 in 2019)",
      date: "2024 Lok Sabha affidavit header",
      allegation: "2024 affidavit declares 3 pending criminal cases (3 serious) vs 4 in 2019; Hindu 2024 reports ‘Yes (3)’. Nature is not further broken out in header — detailed IPC sections per full affidavit PDF needed for line-item.",
      context: "Cases counted in header differ from Sohrabuddin/Ishrat (already discharged/clean chit) — 2024 pending are separate, likely protest/election-related sections (exact sections require affidavit PDF per ECI).",
      responseOrStatus: "No ‘Cases where Convicted’ — none. No disqualification; candidacy valid.",
      citationIds: ["myneta2024Shah", "theHinduAmitBio", "mynetaCompareShah"],
    },
  ],
  citations: {
    wiki: {
      label: "wiki",
      publisher: "Wikipedia — Amit Shah",
      title: "Amit Shah",
      url: "https://en.wikipedia.org/wiki/Amit_Shah",
      accessedOn: "30 August 2026",
    },
    britannica: {
      label: "britannica",
      publisher: "Encyclopædia Britannica",
      title: "Amit Shah — Indian Politician, BJP Leader, Career, Family",
      url: "https://www.britannica.com/biography/Amit-Shah",
      accessedOn: "30 August 2026",
    },
    bjpBio: {
      label: "bjpBio",
      publisher: "Bharatiya Janata Party — Official Website",
      title: "Shri Amit Shah — Born 22 Oct 1964, early life, BJP career, President 2014–20, Home Minister",
      url: "https://www.bjp.org/shri-amit-shah",
      accessedOn: "30 August 2026",
    },
    mhaBio: {
      label: "mhaBio",
      publisher: "Ministry of Home Affairs, Government of India",
      title: "Union Home Minister Shri Amit Shah — Meet the Minister",
      url: "https://www.mha.gov.in/en/about-us/meet-the-minister/union-home-minister",
      accessedOn: "30 August 2026",
    },
    amitshahSite: {
      label: "amitshahSite",
      publisher: "Amit Shah — Official Website",
      title: "Amitbhai Anilchandra Shah: An Introduction & Timeline",
      url: "https://www.amitshah.co.in/about",
      accessedOn: "30 August 2026",
    },
    censusBio: {
      label: "censusBio",
      publisher: "Office of the Registrar General & Census Commissioner, India",
      title: "Union Home Minister, Shri Amit Shah — Biodata (Eng-Shri_Amit_Shah PDF)",
      url: "https://censusindia.gov.in/census.website/sites/default/files/2022-04/Eng-Shri_Amit_Shah.pdf",
      accessedOn: "30 August 2026",
    },
    timesNowCV: {
      label: "timesNowCV",
      publisher: "Times Now News — Education",
      title: "From Ahmedabad University To Home Minister: Check Amit Shah's CV (61st birthday, 22 Oct 2025)",
      url: "https://www.timesnownews.com/education/from-ahmedabad-university-to-home-minister-check-amit-shahs-cv-article-153035762",
      accessedOn: "30 August 2026",
    },
    pibShahAssume: {
      label: "pibShahAssume",
      publisher: "Press Information Bureau, Government of India",
      title: "Shri Amit Shah assumes charge as Union Home Minister (1 Jun 2019) — five-term MLA, Rajya Sabha 2017–19",
      url: "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=1573071",
      accessedOn: "30 August 2026",
    },
    ramnath301: {
      label: "ramnath301",
      publisher: "Rashtrapati Bhavan",
      title: "Allocation of portfolios among Union Council of Ministers (31 May 2019) — Amit Shah: Home",
      url: "https://ramnathkovind.nic.in/pr310519.html",
      accessedOn: "30 August 2026",
    },
    theHinduBusinessLine2024: {
      label: "theHinduBusinessLine2024",
      publisher: "The Hindu BusinessLine — ANI",
      title: "Modi Cabinet 2024: Amit Shah sworn in again (Gandhinagar margin 7,44,716, 10,10,972 votes) — 9 Jun 2024",
      url: "https://www.thehindubusinessline.com/news/national/modi-cabinet-2024-amit-shah-sworn-in-as-union-minister-in-prime-minister-modis-30-cabinet/article68270258.ece",
      accessedOn: "30 August 2026",
    },
    rajasthanAct: {
      label: "rajasthanAct",
      publisher: "India Code / Rajasthan Legislative Assembly",
      title: "Rajasthan Legislative Assembly (Officers & Members Emoluments & Pension) Act, 1956 — §4 (Members' salary) — pattern for Gujarat",
      url: "https://www.indiacode.nic.in/handle/123456789/18773?locale=en",
      accessedOn: "30 August 2026",
    },
    bhaskarRajasthan: {
      label: "bhaskarRajasthan",
      publisher: "Bhaskar English",
      title: "Rajasthan MLAs likely to get 10% salary hike (basic ₹40k→₹44k, total ~₹1.47 lakh pm) — 23 Jul 2025",
      url: "https://www.bhaskarenglish.in/local/rajasthan/news/mlas-salary-and-ex-mlas-pension-to-rise-in-rajasthan-government-proposes-10-hike-in-basic-pay-pension-hike-details-yet-to-be-finalised-135517628.html",
      accessedOn: "30 August 2026",
    },
    acadlogMLA: {
      label: "acadlogMLA",
      publisher: "Acadlog",
      title: "Rajasthan MLA Salary: Complete Details (basic + allowances breakdown)",
      url: "https://acadlog.com/updates/blog/rajasthan-mla-salary-complete-details",
      accessedOn: "30 August 2026",
    },
    mpSalaryGazette: {
      label: "mpSalaryGazette",
      publisher: "Ministry of Parliamentary Affairs — Gazette of India",
      title: "G.S.R. 188(E) — 24% hike: salary ₹1,00,000→₹1,24,000 pm (eff. 1 Apr 2023, notified 24 Mar 2025)",
      url: "https://getapi.indiatvnews.com/doc/261888.pdf",
      accessedOn: "30 August 2026",
    },
    theHinduSalary: {
      label: "theHinduSalary",
      publisher: "The Hindu",
      title: "Centre notifies 24% hike in salaries, pensions for MPs",
      url: "https://www.thehindu.com/news/national/centre-notifies-24-hike-in-salaries-pensions-for-mps/article69368455.ece",
      accessedOn: "30 August 2026",
    },
    bsSalary: {
      label: "bsSalary",
      publisher: "Business Standard",
      title: "Hike in MP Salary in 2025: MPs to get ₹1.24 lakh monthly salary",
      url: "https://www.business-standard.com/india-news/members-of-parliament-salary-pension-allowance-increase-government-125032400774_1.html",
      accessedOn: "30 August 2026",
    },
    etSalary: {
      label: "etSalary",
      publisher: "The Economic Times",
      title: "Centre approves 24% salary hike for MPs: Monthly income rises to Rs 1.24 lakh (assured ₹2.81 lakh incl. allowances)",
      url: "https://economictimes.indiatimes.com/news/politics-and-nation/centre-approves-24-salary-hike-for-mps-monthly-income-rises-to-2-81l/articleshow/119438959.cms",
      accessedOn: "30 August 2026",
    },
    officersParliamentAct: {
      label: "officersParliamentAct",
      publisher: "Indian Kanoon / Gazette of India",
      title: "Salaries and Allowances of Officers of Parliament Act, 1953 (Act 20 of 1953) §§3–5 — residence & sumptuary",
      url: "https://indiankanoon.org/doc/1534878/",
      accessedOn: "30 August 2026",
    },
    article97: {
      label: "article97",
      publisher: "Constitution of India / Lexibal",
      title: "Article 97 — Salaries and allowances of presiding officers and Second Schedule fallback",
      url: "https://lexibal.com/article-97-salaries-presiding-officers/",
      accessedOn: "30 August 2026",
    },
    nevaAmenities: {
      label: "nevaAmenities",
      publisher: "Ministry of Parliamentary Affairs — NeVA",
      title: "Amenities to Members / Officers — salary sumptuary sheet (Cabinet Minister scale)",
      url: "https://cms.neva.gov.in/NeVA/RS/FileStructures/FooterCommonContent/ac06fbd1-f5ef-4425-9bb3-971532e84357.pdf",
      accessedOn: "30 August 2026",
    },
    myneta2024Shah: {
      label: "myneta2024Shah",
      publisher: "Association for Democratic Reforms — MyNeta (ECI affidavit)",
      title: "Amit Shah — Lok Sabha 2024, Gandhinagar — Affidavit (₹65,67,12,498 assets, ₹42L liabilities, 3 cases)",
      url: "https://www.myneta.info/LokSabha2024/candidate.php?candidate_id=4427",
      accessedOn: "30 August 2026",
    },
    myneta2019Shah: {
      label: "myneta2019Shah",
      publisher: "MyNeta — ADR (ECI affidavit)",
      title: "Amit Shah — Lok Sabha 2019, Gandhinagar — Affidavit (₹40,32,75,307, 4 cases)",
      url: "http://www.myneta.info/LokSabha2019/candidate.php?candidate_id=8016",
      accessedOn: "30 August 2026",
    },
    mynetaCompareShah: {
      label: "mynetaCompareShah",
      publisher: "MyNeta — ADR",
      title: "Amit Shah — Asset & cases comparison (2007, 2012, 2019, 2024) — 12th Pass header",
      url: "https://myneta.info/compare_profile.php?group_id=FEFviyNfhffzGoSup8aJ",
      accessedOn: "30 August 2026",
    },
    mynetaCompAmit: {
      label: "mynetaCompAmit",
      publisher: "MyNeta — ADR",
      title: "Asset comparison Amit Shah: Gandhinagar — 2024 vs 2019 (movable 42.8 Cr vs 23.55 Cr, total 65.67 vs 40.32 Cr)",
      url: "https://www.myneta.info/LokSabha2024/index.php?action=affidavitComparison&id1=4427&id2=8016&myneta_folder2=LokSabha2019",
      accessedOn: "30 August 2026",
    },
    adrAmitCompare: {
      label: "adrAmitCompare",
      publisher: "ADR / MyNeta",
      title: "Amit Shah — Affidavit comparison header (Gujarat 2007 ₹5.57 Cr → Lok Sabha 2024 ₹65.67 Cr)",
      url: "https://myneta.info/compare_profile.php?group_id=FEFviyNfhffzGoSup8aJ",
      accessedOn: "30 August 2026",
    },
    etAmitAsset24: {
      label: "etAmitAsset24",
      publisher: "The Economic Times",
      title: "Lok Sabha election: Amit Shah and his wife own assets worth over Rs 65.67 crore, affidavit reveals (21 Apr 2024) — +100% in 5y, shares ₹17.46 Cr, no vehicle",
      url: "https://economictimes.indiatimes.com/news/india/lok-sabha-election-amit-shah-and-his-wife-own-assets-worth-over-rs-65-67-crore-affidavit-reveals/articleshow/109472590.cms",
      accessedOn: "30 August 2026",
    },
    theHinduAmitBio: {
      label: "theHinduAmitBio",
      publisher: "The Hindu — Elections / ADR",
      title: "Amit Shah — BJP candidate bio: Gandhinagar 2024 — ₹65.7 Cr assets, ₹42.1L liabilities, ₹1.1 Cr income, 3 cases (3 serious) — 7 May 2024 poll",
      url: "https://www.thehindu.com/elections/candidates/LokSabha2024/amit-shah-4427/",
      accessedOn: "30 August 2026",
    },
    toIAmitAsset19: {
      label: "toIAmitAsset19",
      publisher: "The Times of India",
      title: "Amit Shah declares assets worth Rs 30.49 crore (31 Mar 2019) — movable ₹18.24 Cr + immovable ₹12.24 Cr, wife ₹8.35 Cr, no vehicle, ITR growth",
      url: "https://timesofindia.indiatimes.com/city/ahmedabad/shah-declares-assets-worth-rs-30-49-crore/articleshow/68650995.cms",
      accessedOn: "30 August 2026",
    },
    indianExpressSohrabuddin: {
      label: "indianExpressSohrabuddin",
      publisher: "The Indian Express",
      title: "CBI Court gives clean chit to Amit Shah in Sohrabuddin Sheikh encounter case — Judge M. B. Gosavi discharge 31 Dec 2014 (hearsay, political reasons)",
      url: "https://indianexpress.com/article/india/india-others/amit-shah-gets-relief-in-sohrabuddin-encounter-case-court-drops-charges-against-him/",
      accessedOn: "30 August 2026",
    },
    bbcSohrabuddin: {
      label: "bbcSohrabuddin",
      publisher: "BBC News",
      title: "Sohrabuddin Sheikh killing: India court clears Amit Shah — arrested Jul 2010, bailed Oct 2010, trial shifted to Mumbai 2012",
      url: "https://www.bbc.com/news/world-asia-india-30632852",
      accessedOn: "30 August 2026",
    },
    bbcAcquittal: {
      label: "bbcAcquittal",
      publisher: "BBC News (via special court 2018)",
      title: "Sohrabuddin — context of 2018 acquittal of 22 and discharge logic (hearsay, official duty calls)",
      url: "https://www.bbc.com/news/world-asia-india-30632852",
      accessedOn: "30 August 2026",
    },
    timesOfIndiaSohrabuddin: {
      label: "timesOfIndiaSohrabuddin",
      publisher: "The Times of India — Bombay HC 8 May 2026",
      title: "Bombay HC upholds acquittal of 21 cops and civilian in Sohrab ‘fake encounter’ case — appeals meritless",
      url: "https://timesofindia.indiatimes.com/city/mumbai/bombay-hc-upholds-acquittal-of-21-cops-and-civilian-in-sohrab-fake-encounter-case/articleshow/130946504.cms",
      accessedOn: "30 August 2026",
    },
    supremeCourtReject: {
      label: "supremeCourtReject",
      publisher: "The Indian Express — Supreme Court",
      title: "Sohrabuddin encounter: Supreme Court rejects plea to re-open Amit Shah's case — Harsh Mander locus dismissed 1 Aug 2016 (‘cannot be interminably prosecuted’)",
      url: "https://indianexpress.com/article/india/india-news-india/sohrabuddin-encounter-supreme-court-rejects-plea-to-re-open-shah-case-2948313/",
      accessedOn: "30 August 2026",
    },
    indianExpressExplain: {
      label: "indianExpressExplain",
      publisher: "The Indian Express — Explained",
      title: "Why Bombay HC upheld acquittal of 22 in Sohrabuddin encounter case — 2018 S.J. Sharma judgment (no conspiracy, no sanction CrPC 197, 92 hostile)",
      url: "https://indianexpress.com/article/explained/explained-law/sohrabuddin-encounter-case-bombay-hc-upholds-acquittal-10677200/",
      accessedOn: "30 August 2026",
    },
    timesOfIndiaIshrat: {
      label: "timesOfIndiaIshrat",
      publisher: "The Times of India",
      title: "Ishrat Jahan encounter case: CBI gives 'clean chit' to Amit Shah — no sufficient evidence (7 May 2014)",
      url: "https://timesofindia.indiatimes.com/india/ishrat-jahan-encounter-case-cbi-gives-clean-chit-to-modi-aide-amit-shah/articleshow/34776773.cms",
      accessedOn: "30 August 2026",
    },
    ndtvIshrat: {
      label: "ndtvIshrat",
      publisher: "NDTV",
      title: "CBI Gives Clean Chit to Amit Shah in Ishrat Jahan Case (7 May 2014) — no chargesheet, 11 policemen + 4 IB officers chargesheeted",
      url: "https://www.ndtv.com/india-news/cbi-gives-clean-chit-to-narendra-modi-aide-amit-shah-in-ishrat-jahan-case-560585",
      accessedOn: "30 August 2026",
    },
    economicTimesIshrat: {
      label: "economicTimesIshrat",
      publisher: "The Economic Times",
      title: "Ishrat fake encounter case: CBI questions Amit Shah — Vanzara resignation letter (‘conscious policy’, 12 Oct 2013)",
      url: "https://economictimes.indiatimes.com/news/politics-and-nation/ishrat-fake-encounter-case-cbi-questions-amit-shah/articleshow/24048310.cms",
      accessedOn: "30 August 2026",
    },
    pibArt370: {
      label: "pibArt370",
      publisher: "Press Information Bureau — Ministry of Home Affairs",
      title: "Union Home Minister Amit Shah welcomes SC ruling upholding abrogation of Article 370 (11 Dec 2023) — 5 Aug 2019 decision",
      url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1984951",
      accessedOn: "30 August 2026",
    },
    indianExpressArt370: {
      label: "indianExpressArt370",
      publisher: "The Indian Express",
      title: "Move to scrap J&K special status: Cards close to his chest, Amit Shah surprises Oppn, most ministers — 5 Aug 2019 orchestration",
      url: "https://indianexpress.com/article/india/move-to-scrap-jk-special-status-cards-close-to-his-chest-amit-shah-surprises-oppn-most-ministers-5880896/",
      accessedOn: "30 August 2026",
    },
    firstpostArt370: {
      label: "firstpostArt370",
      publisher: "Firstpost — Explainers",
      title: "Explained: Inside the secret exercise headed by Amit Shah to abrogate Article 370 — Parliament complex office, Doval/Mehta coordination",
      url: "https://www.firstpost.com/explainers/jammu-kashmir-amit-shah-abrogation-article-370-fallout-anniversary-security-peace-12956792.html",
      accessedOn: "30 August 2026",
    },
    timesNowArt370: {
      label: "timesNowArt370",
      publisher: "Times Now News",
      title: "Article 370, CAA & New Criminal Laws: Amit Shah's 3 Big Decisions as Longest-Serving Home Minister (6+ years, 5 Aug 2019, 1 Jul 2024 codes)",
      url: "https://www.timesnownews.com/india/article-370-caa-new-criminal-laws-amit-shahs-3-big-decisions-as-indias-longest-serving-home-minister-article-152417209",
      accessedOn: "30 August 2026",
    },
    scrollCAA: {
      label: "scrollCAA",
      publisher: "Scroll.in",
      title: "CAA protests: Five times Amit Shah linked the Citizenship Act to the NRC (1 May 2019 tweet ‘First CAB, then NRC’) — 20 Dec 2019",
      url: "https://scroll.in/article/947436/who-is-linking-citizenship-act-to-nrc-here-are-five-times-amit-shah-did-so",
      accessedOn: "30 August 2026",
    },
    wireCAAdodge: {
      label: "wireCAAdodge",
      publisher: "The Wire",
      title: "Amit Shah Dodges Question of ‘Chronology’ between CAA and NRC, Invokes ‘Akhand Bharat’ — 14 Mar 2024 (’There is no NRC now’)",
      url: "https://m.thewire.in/article/government/amit-shah-dodges-question-of-chronology-between-caa-and-nrc-invokes-akhand-bharat",
      accessedOn: "30 August 2026",
    },
    outlookCAA: {
      label: "outlookCAA",
      publisher: "Outlook India",
      title: "‘CAA Will Never Be Taken Back’: Home Minister Amit Shah (ANI 14 Mar 2024, sovereign decision, rules before polls)",
      url: "https://www.outlookindia.com/national/amit-shah-ani-interview-citizenship-amendment-act-caa-will-never-be-taken-back",
      accessedOn: "30 August 2026",
    },
    theHinduCAA: {
      label: "theHinduCAA",
      publisher: "The Hindu — PTI",
      title: "CAA will be implemented before Lok Sabha election, says Amit Shah (10 Feb 2024, ET NOW Summit)",
      url: "https://www.thehindu.com/news/national/caa-will-be-implemented-before-lok-sabha-election-says-amit-shah/article67833557.ece",
      accessedOn: "30 August 2026",
    },
  },
  lastVerified: "30 August 2026",
  disclaimer:
    "This profile aggregates role-relevant public facts about a Union Cabinet Minister from official rosters (Lok Sabha Secretariat / Digital Sansad, MHA, PIB, ECI affidavits via ADR/Myneta) and attributed reputable reporting for context. Secondary detail is citation-linked; where sources diverge (education ‘12th Pass’ affidavit header vs ‘B.Sc. Biochemistry’ biography; Mumbai/Mansa birth phrasing), variation is noted. No private contact/address/identifier published. Court outcomes are as pronounced; ‘alleged’ qualifiers reflect the pronounced stage. For authoritative current status, see sansad.in, mha.gov.in and the ECI affidavit PDFs.",
};
